'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { WorkspaceNav } from '@/ui/workspace-nav';
import { LoadingBlock, StatusBadge, StatusNotice } from '@/ui/feedback';
import { ReadRecoveryNotice } from '@/ui/read-recovery-notice';
import { AdminApiError } from '@/admin/api';
import { adminApi, type Employee, type Site } from '@/admin/api';
import { minutes } from '@/admin/presentation';
import { managerApi, type TeamSnapshot } from './api';
import type { CorrectionRequest } from '@/corrections/contracts';
import type { LeaveRequest } from '@/leave-requests/contracts';
import { managerHomeItems,type ManagerHoliday } from './home';
import { useModuleEnabled } from '@/modules/ui';

export function ManagerNav(){const planningEnabled=useModuleEnabled('shift_planning');return <WorkspaceNav ariaLabel="Espacio de responsable" variant="manager" items={[{href:'/manager',label:'Mi centro'},{href:'/manager/team',label:'Equipo'},...(planningEnabled?[{href:'/manager/planning',label:'Cuadrante'}]:[]),{href:'/manager/attention',label:'Atención'}]} />}
const kind=(status:CorrectionRequest['status'])=>status==='approved'?'success':status==='rejected'?'error':'warning';

export function ManagerDashboard(){
  const planningEnabled=useModuleEnabled('shift_planning');
  const [state,setState]=useState<{sites:Site[];employees:Employee[];corrections:CorrectionRequest[];leaveRequests:LeaveRequest[];holidays:ManagerHoliday[]}>({sites:[],employees:[],corrections:[],leaveRequests:[],holidays:[]});
  const [loading,setLoading]=useState(true);const [failure,setFailure]=useState<unknown>();
  const load=()=>{setLoading(true);setFailure(undefined);Promise.all([adminApi.sites(),adminApi.employees(),adminApi.corrections(),managerRead<{leaveRequests:LeaveRequest[]}>('/api/v1/leave-requests'),planningEnabled?managerRead<{holidays:ManagerHoliday[]}>('/api/v1/shift-planning/my-center/catalog'):Promise.resolve({holidays:[]})]).then(([sites,employees,corrections,leaves,catalog])=>setState({sites,employees,corrections,leaveRequests:leaves.leaveRequests,holidays:catalog.holidays})).catch(setFailure).finally(()=>setLoading(false));};
  useEffect(()=>{void load();},[planningEnabled]);
  const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid'}).format(new Date());const home=useMemo(()=>managerHomeItems(state.corrections,state.leaveRequests,state.holidays,today),[state,today]);const siteNames=new Map(state.sites.map(site=>[site.id,site.name]));
  return <main className="admin-shell"><ManagerNav/><header><p className="eyebrow">RESPONSABLE DE CENTRO</p><h1>Centro operativo</h1><p className="subtle">Prioriza decisiones pendientes y excepciones de tus centros autorizados, sin monitorización individual ni decisiones automáticas.</p></header>{failure?<ReadRecoveryNotice status={failure instanceof AdminApiError?failure.status:undefined} onRetry={load}/>:loading?<LoadingBlock>Preparando el centro operativo…</LoadingBlock>:<div className="manager-home"><section className="manager-home__metrics" aria-label="Resumen operativo"><article><strong>{home.pendingCorrectionCount}</strong><span>Correcciones pendientes</span><Link href="/manager/attention?type=correction">Abrir atención</Link></article><article><strong>{home.pendingLeaveCount}</strong><span>Solicitudes pendientes</span><Link href="/manager/attention?type=leave">Abrir atención</Link></article><article><strong>{state.employees.length}</strong><span>Personas en el ámbito</span><Link href="/manager/team">Ver equipo</Link></article></section><section className="admin-section manager-home__section"><div className="section-heading"><div><h2>Decisiones pendientes</h2><p className="subtle">Vista previa cronológica; las decisiones se realizan en sus flujos existentes.</p></div><Link href="/manager/attention">Ver toda la atención</Link></div>{home.decisions.length?<ul className="admin-list">{home.decisions.slice(0,5).map(item=><li key={`${item.kind}-${item.id}`}><span><StatusBadge kind="warning">Pendiente</StatusBadge><strong>{item.label}</strong><small>{item.kind==='correction'?'Requiere revisión de corrección':'Requiere decisión sobre solicitud'}</small></span><Link href={item.href}>Revisar</Link></li>)}</ul>:<p className="subtle">No hay decisiones pendientes en tus centros.</p>}</section><section className="admin-section manager-home__section"><div className="section-heading"><div><h2>Próximas excepciones</h2><p className="subtle">Festivos y ausencias aprobadas por centro. No se muestran comentarios ni motivos personales.</p></div>{planningEnabled&&<Link href="/manager/planning">Abrir cuadrante</Link>}</div>{home.exceptions.length?<ul className="admin-list">{home.exceptions.slice(0,5).map((item,index)=><li key={`${item.siteId}-${item.date}-${item.label}-${index}`}><span><strong>{item.label}</strong><small>{item.date} · {siteNames.get(item.siteId)??'Centro autorizado'}</small></span></li>)}</ul>:<p className="subtle">No hay excepciones próximas configuradas en tus centros.</p>}</section></div>}</main>;
}

type Envelope<T>={data:T};
async function managerRead<T>(url:string){const response=await fetch(url,{credentials:'same-origin'});const body=await response.json().catch(()=>null) as Envelope<T>|null;if(!response.ok||!body)throw new AdminApiError(response.status);return body.data;}

const imputationLabel:Record<TeamSnapshot['imputation']['status'],string>={without_records:'Sin imputación registrada',recorded:'Imputación registrada',with_incidents:'Requiere revisión'};
export function ManagerTeam(){const [items,setItems]=useState<TeamSnapshot[]>([]);const [loading,setLoading]=useState(true);const [failure,setFailure]=useState<unknown>();const load=()=>{setLoading(true);setFailure(undefined);managerApi.team().then(setItems).catch(setFailure).finally(()=>setLoading(false));};useEffect(()=>{void load();},[]);return <main className="admin-shell"><ManagerNav/><header><p className="eyebrow">RESPONSABLE DE CENTRO</p><h1>Equipo · hoy</h1><p className="subtle">Consulta la imputación diaria de tus centros para priorizar una revisión humana. No hay seguimiento continuo, ranking ni decisiones automáticas.</p></header>{failure?<ReadRecoveryNotice status={failure instanceof AdminApiError?failure.status:undefined} onRetry={load}/>:loading?<LoadingBlock>Consultando el estado operativo del equipo…</LoadingBlock>:<section className="admin-section manager-team"><div className="section-heading"><div><h2>Imputaciones del día</h2><p className="subtle">La comparación es informativa y sólo aparece cuando existe una jornada publicada.</p></div><button className="secondary" onClick={load}>Actualizar</button></div>{!items.length?<p className="subtle">No hay personas disponibles en tu ámbito.</p>:<ul className="manager-team__list">{items.map(item=><li key={item.employee.id}><div><strong>{item.employee.displayName}</strong><small>{item.site.name} · {item.laborDate}</small></div><dl><div><dt>Imputado</dt><dd>{minutes(item.imputation.effectiveMinutes)}{item.imputation.expectedMinutes!==null&&<> <span aria-hidden="true">/</span> {minutes(item.imputation.expectedMinutes)}</>}</dd></div><div><dt>Jornada publicada</dt><dd>{item.imputation.expectedMinutes===null?'No disponible':minutes(item.imputation.expectedMinutes)}</dd></div><div><dt>Ubicación</dt><dd>{item.locationVerification==='punctual_verified'?'Verificación puntual registrada':'Sin verificación puntual'}</dd></div></dl><div className="manager-team__actions"><StatusBadge kind={item.imputation.status==='with_incidents'?'warning':item.imputation.status==='recorded'?'success':'info'}>{imputationLabel[item.imputation.status]}</StatusBadge>{item.pending.corrections>0&&<StatusBadge kind="warning"><span aria-hidden="true">⚠ </span>{item.pending.corrections} {item.pending.corrections===1?'corrección pendiente':'correcciones pendientes'}</StatusBadge>}{item.pending.leaveRequests>0&&<StatusBadge kind="warning"><span aria-hidden="true">⚠ </span>{item.pending.leaveRequests} {item.pending.leaveRequests===1?'solicitud pendiente':'solicitudes pendientes'}</StatusBadge>}<Link className="ui-action ui-action--secondary" href={`/manager/team/${item.employee.id}`}>Ver detalle</Link></div></li>)}</ul>}</section>}</main>}

export function ManagerCorrections(){const [items,setItems]=useState<CorrectionRequest[]>([]);const [failure,setFailure]=useState<string>();useEffect(()=>{adminApi.corrections().then(value=>setItems(value.filter(item=>item.status==='pending'))).catch(error=>setFailure(error instanceof Error?error.message:'No se pudieron cargar las correcciones.'));},[]);return <main className="admin-shell"><ManagerNav/><header><p className="eyebrow">RESPONSABLE DE CENTRO</p><h1>Correcciones pendientes</h1><p className="subtle">Solicitudes de corrección pendientes dentro de tu ámbito autorizado.</p></header>{failure&&<StatusNotice kind="error">{failure}</StatusNotice>}<section className="admin-section">{!items.length?<p className="subtle">No hay correcciones pendientes en tu ámbito.</p>:<ul className="admin-list">{items.map(item=><li key={item.id}><span><StatusBadge kind={kind(item.status)}>Pendiente</StatusBadge><strong>{item.laborDate}</strong><small>{item.reason}</small></span><Link href={`/manager/corrections/${item.id}`}>Revisar</Link></li>)}</ul>}</section></main>}
