'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { WorkspaceNav } from '@/ui/workspace-nav';
import { LoadingBlock, StatusBadge, StatusNotice } from '@/ui/feedback';
import { ReadRecoveryNotice } from '@/ui/read-recovery-notice';
import { AdminApiError } from '@/admin/api';
import { adminApi, type Employee, type Site } from '@/admin/api';
import type { CorrectionRequest } from '@/corrections/contracts';
import type { LeaveRequest } from '@/leave-requests/contracts';
import { managerHomeItems,type ManagerHoliday } from './home';

export function ManagerNav(){return <WorkspaceNav ariaLabel="Espacio de responsable" variant="manager" items={[{href:'/manager',label:'Mi centro'},{href:'/manager/team',label:'Equipo'},{href:'/manager/planning',label:'Cuadrante'},{href:'/manager/corrections',label:'Correcciones'},{href:'/manager/leave-requests',label:'Solicitudes'}]} />}
const kind=(status:CorrectionRequest['status'])=>status==='approved'?'success':status==='rejected'?'error':'warning';

export function ManagerDashboard(){
  const [state,setState]=useState<{sites:Site[];employees:Employee[];corrections:CorrectionRequest[];leaveRequests:LeaveRequest[];holidays:ManagerHoliday[]}>({sites:[],employees:[],corrections:[],leaveRequests:[],holidays:[]});
  const [loading,setLoading]=useState(true);const [failure,setFailure]=useState<unknown>();
  const load=()=>{setLoading(true);setFailure(undefined);Promise.all([adminApi.sites(),adminApi.employees(),adminApi.corrections(),managerRead<{leaveRequests:LeaveRequest[]}>('/api/v1/leave-requests'),managerRead<{holidays:ManagerHoliday[]}>('/api/v1/shift-planning/my-center/catalog')]).then(([sites,employees,corrections,leaves,catalog])=>setState({sites,employees,corrections,leaveRequests:leaves.leaveRequests,holidays:catalog.holidays})).catch(setFailure).finally(()=>setLoading(false));};
  useEffect(()=>{void load();},[]);
  const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid'}).format(new Date());const home=useMemo(()=>managerHomeItems(state.corrections,state.leaveRequests,state.holidays,today),[state,today]);const siteNames=new Map(state.sites.map(site=>[site.id,site.name]));
  return <main className="admin-shell"><ManagerNav/><header><p className="eyebrow">RESPONSABLE DE CENTRO</p><h1>Centro operativo</h1><p className="subtle">Prioriza decisiones pendientes y excepciones de tus centros autorizados, sin monitorización individual ni decisiones automáticas.</p></header>{failure?<ReadRecoveryNotice status={failure instanceof AdminApiError?failure.status:undefined} onRetry={load}/>:loading?<LoadingBlock>Preparando el centro operativo…</LoadingBlock>:<div className="manager-home"><section className="manager-home__metrics" aria-label="Resumen operativo"><article><strong>{home.pendingCorrectionCount}</strong><span>Correcciones pendientes</span><Link href="/manager/corrections">Revisar correcciones</Link></article><article><strong>{home.pendingLeaveCount}</strong><span>Solicitudes pendientes</span><Link href="/manager/leave-requests">Revisar solicitudes</Link></article><article><strong>{state.employees.length}</strong><span>Personas en el ámbito</span><Link href="/manager/team">Ver equipo</Link></article></section><section className="admin-section manager-home__section"><div className="section-heading"><div><h2>Decisiones pendientes</h2><p className="subtle">Accede al flujo existente para revisar y decidir.</p></div></div>{home.decisions.length?<ul className="admin-list">{home.decisions.slice(0,5).map(item=><li key={`${item.kind}-${item.id}`}><span><StatusBadge kind="warning">Pendiente</StatusBadge><strong>{item.label}</strong><small>{item.kind==='correction'?'Requiere revisión de corrección':'Requiere decisión sobre solicitud'}</small></span><Link href={item.href}>Revisar</Link></li>)}</ul>:<p className="subtle">No hay decisiones pendientes en tus centros.</p>}</section><section className="admin-section manager-home__section"><div className="section-heading"><div><h2>Próximas excepciones</h2><p className="subtle">Festivos y ausencias aprobadas por centro. No se muestran comentarios ni motivos personales.</p></div><Link href="/manager/planning">Abrir cuadrante</Link></div>{home.exceptions.length?<ul className="admin-list">{home.exceptions.slice(0,5).map((item,index)=><li key={`${item.siteId}-${item.date}-${item.label}-${index}`}><span><strong>{item.label}</strong><small>{item.date} · {siteNames.get(item.siteId)??'Centro autorizado'}</small></span></li>)}</ul>:<p className="subtle">No hay excepciones próximas configuradas en tus centros.</p>}</section><section className="admin-section manager-home__section"><h2>Acciones del centro</h2><div className="manager-home__actions"><Link href="/manager/planning">Gestionar cuadrante</Link><Link href="/manager/corrections">Abrir correcciones</Link><Link href="/manager/leave-requests">Abrir solicitudes</Link></div></section></div>}</main>;
}

type Envelope<T>={data:T};
async function managerRead<T>(url:string){const response=await fetch(url,{credentials:'same-origin'});const body=await response.json().catch(()=>null) as Envelope<T>|null;if(!response.ok||!body)throw new AdminApiError(response.status);return body.data;}

export function ManagerTeam(){const [items,setItems]=useState<Employee[]>([]);const [failure,setFailure]=useState<unknown>();const load=()=>{setFailure(undefined);adminApi.employees().then(setItems).catch(setFailure);};useEffect(load,[]);return <main className="admin-shell"><ManagerNav/><header><p className="eyebrow">RESPONSABLE DE CENTRO</p><h1>Equipo autorizado</h1><p className="subtle">Personas pertenecientes exclusivamente a tus centros autorizados.</p></header>{Boolean(failure)&&<ReadRecoveryNotice status={failure instanceof AdminApiError?failure.status:undefined} onRetry={load}/>}<section className="admin-section">{!items.length&&!failure?<p className="subtle">No hay personas disponibles en tu ámbito.</p>:<ul className="admin-list">{items.map(item=><li key={item.id}><span><strong>{item.displayName}</strong><small>Persona dentro de tu ámbito autorizado</small></span></li>)}</ul>}</section></main>}

export function ManagerCorrections(){const [items,setItems]=useState<CorrectionRequest[]>([]);const [failure,setFailure]=useState<string>();useEffect(()=>{adminApi.corrections().then(value=>setItems(value.filter(item=>item.status==='pending'))).catch(error=>setFailure(error instanceof Error?error.message:'No se pudieron cargar las correcciones.'));},[]);return <main className="admin-shell"><ManagerNav/><header><p className="eyebrow">RESPONSABLE DE CENTRO</p><h1>Correcciones pendientes</h1><p className="subtle">Solicitudes de corrección pendientes dentro de tu ámbito autorizado.</p></header>{failure&&<StatusNotice kind="error">{failure}</StatusNotice>}<section className="admin-section">{!items.length?<p className="subtle">No hay correcciones pendientes en tu ámbito.</p>:<ul className="admin-list">{items.map(item=><li key={item.id}><span><StatusBadge kind={kind(item.status)}>Pendiente</StatusBadge><strong>{item.laborDate}</strong><small>{item.reason}</small></span><Link href={`/manager/corrections/${item.id}`}>Revisar</Link></li>)}</ul>}</section></main>}
