import { db } from '@/shared/db';
import { config } from '@/shared/config';
import { assertAuthorized, assertSiteScope, type ScopedActor } from '@/permissions/authorizer';
import { currentCalculation, publishedWorkdayForEmployee } from '@/time-calculation/service';
import { listWorkdays } from '@/admin/service';
import { listCorrections } from '@/corrections/service';
import { listLeaveRequests } from '@/leave-requests/service';

export type TeamOperationalSnapshot={employee:{id:string;displayName:string};site:{id:string;name:string};laborDate:string;imputation:{status:'without_records'|'recorded'|'with_incidents';effectiveMinutes:number;expectedMinutes:number|null;differenceMinutes:number|null};locationVerification:'not_recorded'|'punctual_verified';pending:{corrections:number;leaveRequests:number}};
export type TeamPersonDetail={employee:{id:string;displayName:string};site:{id:string;name:string};workdays:{laborDate:string;effectiveMinutes:number;expectedMinutes:number;incidents:number}[];corrections:{id:string;laborDate:string;status:'pending'|'approved'|'rejected'}[];leaveRequests:{id:string;fromDate:string;toDate:string;category:string;status:'pending'|'approved'|'rejected'|'cancelled'}[]};
type ScopedEmployee={id:string;displayName:string;siteId:string;siteName:string};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid'}).format(new Date());

/** Sólo comunica evidencia operativa; ni coordenadas, ni precisión, ni dispositivo. */
export async function teamOperationalSnapshot(actor:ScopedActor,asOf=new Date().toISOString()):Promise<TeamOperationalSnapshot[]>{
  assertAuthorized(actor,'time-calculation.read:scope');
  const siteIds=actor.scopes?.filter(scope=>scope.type==='site'&&scope.id).map(scope=>scope.id!)??[];const environment=actor.scopes?.some(scope=>scope.type==='environment')??false;
  if(!environment&&!siteIds.length)return [];
  const scope=environment?'':` AND em.site_id = ANY($2::uuid[])`;const params=environment?[config.ENVIRONMENT_ID]:[config.ENVIRONMENT_ID,siteIds];
  const people=(await db.query<ScopedEmployee>(`SELECT DISTINCT ON (e.id) e.id,e.display_name AS "displayName",s.id AS "siteId",s.name AS "siteName" FROM employees e JOIN companies c ON c.id=e.company_id JOIN users u ON u.id=e.user_id AND u.is_active JOIN user_role_assignments ura ON ura.user_id=u.id AND ura.valid_from<=clock_timestamp() AND (ura.valid_to IS NULL OR ura.valid_to>clock_timestamp()) JOIN roles r ON r.id=ura.role_id AND r.code='employee' JOIN employments em ON em.employee_id=e.id AND em.effective_from<=CURRENT_DATE AND (em.effective_to IS NULL OR em.effective_to>CURRENT_DATE) JOIN sites s ON s.id=em.site_id WHERE c.environment_id=$1 AND c.is_active AND e.is_active AND s.is_active${scope} ORDER BY e.id,em.effective_from DESC`,params)).rows;
  return Promise.all(people.map(async person=>{const published=await publishedWorkdayForEmployee(person.id,asOf);const laborDate=published?.laborDate??today();const calculation=await currentCalculation(person.id,laborDate);const verified=(await db.query<{verified:boolean}>(`SELECT EXISTS(SELECT 1 FROM time_events event JOIN time_event_geo_verifications verification ON verification.event_id=event.id WHERE event.employee_id=$1 AND event.labor_date=$2::date) AS verified`,[person.id,laborDate])).rows[0]?.verified??false;const pendingScope=environment?'':` AND site_id=ANY($2::uuid[])`;const pendingParams=environment?[person.id]:[person.id,siteIds];const pending=(await db.query<{corrections:number;leaveRequests:number}>(`SELECT (SELECT count(*)::int FROM correction_requests WHERE employee_id=$1 AND status='pending'${pendingScope}) AS "corrections",(SELECT count(*)::int FROM leave_requests WHERE employee_id=$1 AND status='pending'${pendingScope}) AS "leaveRequests"`,pendingParams)).rows[0]??{corrections:0,leaveRequests:0};return {employee:{id:person.id,displayName:person.displayName},site:{id:person.siteId,name:person.siteName},laborDate,imputation:{status:published?.evidence.status==='recorded'?(calculation?.incidents.length?'with_incidents':'recorded'):'without_records',effectiveMinutes:calculation?.effectiveMinutes??0,expectedMinutes:published?.schedule?.expectedMinutes??null,differenceMinutes:calculation?.differenceMinutes??null},locationVerification:verified?'punctual_verified':'not_recorded',pending};}));
}

async function scopedPerson(actor:ScopedActor,employeeId:string):Promise<ScopedEmployee>{
  assertAuthorized(actor,'time-calculation.read:scope');const person=(await db.query<ScopedEmployee>(`SELECT e.id,e.display_name AS "displayName",s.id AS "siteId",s.name AS "siteName" FROM employees e JOIN companies c ON c.id=e.company_id JOIN users u ON u.id=e.user_id AND u.is_active JOIN user_role_assignments ura ON ura.user_id=u.id AND ura.valid_from<=clock_timestamp() AND (ura.valid_to IS NULL OR ura.valid_to>clock_timestamp()) JOIN roles r ON r.id=ura.role_id AND r.code='employee' JOIN employments em ON em.employee_id=e.id JOIN sites s ON s.id=em.site_id WHERE e.id=$1 AND c.environment_id=$2 AND e.is_active AND s.is_active AND em.effective_from<=CURRENT_DATE AND (em.effective_to IS NULL OR em.effective_to>CURRENT_DATE) ORDER BY em.effective_from DESC LIMIT 1`,[employeeId,config.ENVIRONMENT_ID])).rows[0];if(!person)throw new Error('TEAM_MEMBER_NOT_FOUND');assertSiteScope(actor,person.siteId);return person;
}

/** Detalle de ámbito: estados y fechas, nunca motivos ni comentarios personales. */
export async function teamPersonDetail(actor:ScopedActor,employeeId:string):Promise<TeamPersonDetail>{
  const person=await scopedPerson(actor,employeeId);const [workdays,corrections,leaveRequests]=await Promise.all([listWorkdays(actor,{from:'2000-01-01',to:today(),employeeId,incident:'all',detail:false}),listCorrections(actor,employeeId),listLeaveRequests(actor,false)]);
  return {employee:{id:person.id,displayName:person.displayName},site:{id:person.siteId,name:person.siteName},workdays:await Promise.all(workdays.map(async day=>{const published=await publishedWorkdayForEmployee(employeeId,`${day.calculation.laborDate}T12:00:00.000Z`);return {laborDate:day.calculation.laborDate,effectiveMinutes:day.calculation.effectiveMinutes,expectedMinutes:published?.schedule?.expectedMinutes??0,incidents:day.calculation.incidents.length};})),corrections:corrections.map(item=>({id:item.id,laborDate:item.laborDate,status:item.status})),leaveRequests:leaveRequests.filter(item=>item.employeeId===employeeId).map(item=>({id:item.id,fromDate:item.fromDate,toDate:item.toDate,category:item.category,status:item.status}))};
}
