import { db } from '@/shared/db';
import { appendAudit } from '@/audit/audit-writer';
import { recalculateDaily } from './service';

type OutboxRow={id:string;name:string;payload:{employeeId?:string;laborDate?:string};correlationId:string;attempts:number};
const supported=new Set(['time-event.recorded','time-calculation.recalculation-requested']);

/** Internal monolith consumer. It is safe to run repeatedly; S5 input hashes make materialization idempotent. */
export async function processCalculationOutbox(limit=25){
  const client=await db.connect(); let processed=0; try{await client.query('BEGIN');const rows=(await client.query<OutboxRow>(`SELECT o.id,o.name,o.payload,o.correlation_id AS "correlationId",coalesce(c.attempts,0) AS attempts FROM domain_event_outbox o LEFT JOIN time_calculation_outbox_consumptions c ON c.outbox_id=o.id WHERE o.name=ANY($1) AND coalesce(c.processed_at IS NULL,true) AND coalesce(c.next_attempt_at<=clock_timestamp(),true) ORDER BY o.occurred_at,o.id FOR UPDATE OF o SKIP LOCKED LIMIT $2`,[[...supported],limit])).rows;for(const row of rows){const employeeId=row.payload.employeeId;const laborDate=row.payload.laborDate;if(!employeeId||!laborDate){await client.query(`INSERT INTO time_calculation_outbox_consumptions(outbox_id,attempts,processed_at,last_error_code) VALUES($1,$2,clock_timestamp(),'INVALID_PAYLOAD') ON CONFLICT(outbox_id) DO UPDATE SET attempts=EXCLUDED.attempts,processed_at=EXCLUDED.processed_at,last_error_code=EXCLUDED.last_error_code,updated_at=clock_timestamp()`,[row.id,row.attempts+1]);continue;}try{await recalculateDaily(employeeId,laborDate,undefined,row.correlationId);await client.query(`INSERT INTO time_calculation_outbox_consumptions(outbox_id,attempts,processed_at,last_error_code) VALUES($1,$2,clock_timestamp(),NULL) ON CONFLICT(outbox_id) DO UPDATE SET attempts=EXCLUDED.attempts,processed_at=EXCLUDED.processed_at,last_error_code=NULL,updated_at=clock_timestamp()`,[row.id,row.attempts+1]);processed++;}catch(error){const code=error instanceof Error&&/^[A-Z0-9_]+$/.test(error.message)?error.message:'MATERIALIZATION_FAILED';await client.query(`INSERT INTO time_calculation_outbox_consumptions(outbox_id,attempts,next_attempt_at,last_error_code) VALUES($1,$2,clock_timestamp()+interval '1 minute',$3) ON CONFLICT(outbox_id) DO UPDATE SET attempts=EXCLUDED.attempts,next_attempt_at=EXCLUDED.next_attempt_at,last_error_code=EXCLUDED.last_error_code,updated_at=clock_timestamp()`,[row.id,row.attempts+1,code]);}}await client.query('COMMIT');return {processed};}catch(error){await client.query('ROLLBACK').catch(()=>undefined);throw error;}finally{client.release();}
}

export async function repairCalculationHistory(input:{employeeId:string;laborDate:string;correlationId:string}){const result=await recalculateDaily(input.employeeId,input.laborDate,undefined,input.correlationId);await appendAudit({actorType:'system',action:'time-calculation.history.repaired',resourceType:'daily-calculation',resourceId:result.calculation.id,result:'success',correlationId:input.correlationId,changes:{employeeId:input.employeeId,laborDate:input.laborDate,replayed:result.replayed}});return result;}
