'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ManagerNav } from '@/manager/components';

type Template={id:string;name:string;version:number;status:'draft'|'published'|'retired';expectedMinutes:number;sites:{id:string;name:string}[]}; type Employment={id:string;displayName:string;siteName:string;effectiveFrom:string}; type Assignment={id:string;employmentId:string;effectiveFrom:string;effectiveTo:string|null;status:string;displayName:string;templateSnapshot:{name:string;version:number;segments:{start:string;end:string}[]}};
const duration=(minutes:number)=>`${Math.floor(minutes/60)} h${minutes%60?` ${minutes%60} min`:''}`; const iso=(date:Date)=>date.toISOString().slice(0,10); const monday=(value:string)=>{const date=new Date(`${value}T12:00:00`);const day=(date.getDay()+6)%7;date.setDate(date.getDate()-day);return iso(date);}; const addDays=(value:string,days:number)=>{const date=new Date(`${value}T12:00:00`);date.setDate(date.getDate()+days);return iso(date);}; const labelDate=(value:string)=>new Date(`${value}T12:00:00`).toLocaleDateString('es-ES',{weekday:'short',day:'numeric',month:'short'}); const tomorrow=()=>addDays(iso(new Date()),1);
async function request<T>(url:string,init?:RequestInit){const response=await fetch(url,{credentials:'same-origin',...init});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error?.message??'No se pudo completar la operación.');return body.data as T;}

export function ManagerPlanning(){const [templates,setTemplates]=useState<Template[]>([]);const [employments,setEmployments]=useState<Employment[]>([]);const [assignments,setAssignments]=useState<Assignment[]>([]);const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [week,setWeek]=useState(()=>monday(tomorrow()));const days=useMemo(()=>Array.from({length:7},(_,index)=>addDays(week,index)),[week]);const load=()=>Promise.all([request<{templates:Template[];employments:Employment[]}>('/api/v1/shift-planning/my-center/catalog'),request<Assignment[]>('/api/v1/shift-planning/my-center/assignments')]).then(([data,published])=>{setTemplates(data.templates.filter(template=>template.status==='published'));setEmployments(data.employments);setAssignments(published.filter(item=>item.status==='published'));}).catch(error=>setNotice(error instanceof Error?error.message:'No se pudo cargar el cuadrante.'));useEffect(()=>{void load();},[]);
const publish=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const value=new FormData(form);setBusy(true);setNotice('');try{await request('/api/v1/shift-planning/my-center/assignments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({employmentId:String(value.get('employmentId')),templateId:String(value.get('templateId')),effectiveFrom:String(value.get('effectiveFrom')),reasonCode:'initial_plan'})});form.reset();setNotice('Asignación publicada para el equipo de tu centro.');await load();}catch(error){setNotice(error instanceof Error?error.message:'No se pudo publicar la asignación.');}finally{setBusy(false);}};
const assignmentFor=(employmentId:string,day:string)=>assignments.find(item=>item.employmentId===employmentId&&item.effectiveFrom<=day&&(!item.effectiveTo||item.effectiveTo>day));
return <main className="admin-shell"><ManagerNav/><header><p className="eyebrow">CUADRANTE DE CENTRO</p><h1>Planificación del equipo</h1><p className="subtle">Vista semanal de referencias operativas futuras. Sólo muestra relaciones y plantillas autorizadas para tu centro.</p></header>{notice&&<p className="status-notice status-notice--info" role="status">{notice}</p>}<section className="admin-section"><div className="section-heading"><div><h2>Semana del {new Date(`${week}T12:00:00`).toLocaleDateString('es-ES',{day:'numeric',month:'long',year:'numeric'})}</h2><p className="subtle">Cada celda muestra la jornada publicada o “Sin asignación”.</p></div><div className="planning-actions"><button className="secondary" type="button" onClick={()=>setWeek(value=>addDays(value,-7))}>Semana anterior</button><button className="secondary" type="button" onClick={()=>setWeek(value=>addDays(value,7))}>Semana siguiente</button></div></div><div className="planning-grid-wrap"><table className="planning-grid"><thead><tr><th scope="col">Persona</th>{days.map(day=><th scope="col" key={day}>{labelDate(day)}</th>)}</tr></thead><tbody>{employments.map(employment=><tr key={employment.id}><th scope="row"><strong>{employment.displayName}</strong><small>{employment.siteName}</small></th>{days.map(day=>{const assignment=assignmentFor(employment.id,day);const segment=assignment?.templateSnapshot.segments[0];return <td key={day} className={assignment?'planning-grid__assigned':'planning-grid__empty'}>{assignment?<span title={`${assignment.templateSnapshot.name} · v${assignment.templateSnapshot.version}`}>{segment?`${segment.start} – ${segment.end}`:assignment.templateSnapshot.name}</span>:<span>Sin asignación</span>}</td>;})}</tr>)}</tbody></table></div>{!employments.length&&<p className="subtle">No hay relaciones laborales dentro de tu ámbito.</p>}</section><section className="admin-section"><h2>Asignar y publicar</h2><p className="subtle">Publica sólo una fecha posterior a hoy. El servidor valida centro, relación vigente, plantilla habilitada y solapes antes de guardar.</p><form className="employee-form" onSubmit={(event)=>void publish(event)}><label>Persona y relación laboral<select name="employmentId" required><option value="">Seleccione una relación</option>{employments.map(item=><option key={item.id} value={item.id}>{item.displayName} · {item.siteName}</option>)}</select></label><label>Plantilla<select name="templateId" required><option value="">Seleccione una plantilla</option>{templates.map(item=><option key={item.id} value={item.id}>{item.name} · v{item.version} · {duration(item.expectedMinutes)}</option>)}</select></label><label>Vigente desde<input name="effectiveFrom" type="date" min={tomorrow()} defaultValue={tomorrow()} required/></label><button disabled={busy||!templates.length||!employments.length}>{busy?'Publicando…':'Publicar asignación'}</button></form></section></main>;}
