import { db } from '@/shared/db';
import { config } from '@/shared/config';
import { appendAudit } from '@/audit/audit-writer';
import type { ScopedActor } from '@/permissions/authorizer';
import type { ShiftPlanningModuleStatus } from './contracts';
import type { z } from 'zod';
import type { assignmentInput, moduleStatusInput, templateInput } from './validation';
import { expectedMinutes } from './validation';

type Audit = { actor: ScopedActor; correlationId: string };
const company = async () => (await db.query<{id:string}>('SELECT id FROM companies WHERE environment_id=$1 AND is_active',[config.ENVIRONMENT_ID])).rows[0] ?? null;

export async function moduleStatus(): Promise<ShiftPlanningModuleStatus> { const row=await db.query<{status:ShiftPlanningModuleStatus}>('SELECT cm.status FROM company_modules cm JOIN companies c ON c.id=cm.company_id WHERE c.environment_id=$1 AND cm.module_key=$2',[config.ENVIRONMENT_ID,'shift_planning']); return row.rows[0]?.status ?? 'disabled'; }
export async function setModuleStatus(input:z.infer<typeof moduleStatusInput>,audit:Audit){const c=await company();if(!c)throw new Error('PLANNING_NOT_CONFIGURED');const row=(await db.query<{status:ShiftPlanningModuleStatus}>(`INSERT INTO company_modules(company_id,module_key,status,updated_by_user_id) VALUES($1,'shift_planning',$2,$3) ON CONFLICT(company_id,module_key) DO UPDATE SET status=EXCLUDED.status,version=company_modules.version+1,updated_by_user_id=EXCLUDED.updated_by_user_id,updated_at=clock_timestamp() RETURNING status`,[c.id,input.status,audit.actor.id])).rows[0];await appendAudit({actorType:'user',actorId:audit.actor.id,action:'shift-planning.module.updated',resourceType:'company-module',resourceId:c.id,result:'success',correlationId:audit.correlationId,changes:{module:'shift_planning',status:row.status}});return row;}
const writable = async () => { const status=await moduleStatus(); if(status==='disabled'||status==='paused')throw new Error('PLANNING_MODULE_INACTIVE'); return status; };
const templateColumns = 'id,name,version,status,time_zone AS "timeZone",segments,expected_minutes AS "expectedMinutes"';
const templateListColumns = `t.id,t.name,t.version,t.status,t.time_zone AS "timeZone",t.segments,t.expected_minutes AS "expectedMinutes",
  COALESCE((SELECT jsonb_agg(jsonb_build_object('id',s.id,'name',s.name) ORDER BY s.name)
    FROM planned_shift_template_sites pts JOIN sites s ON s.id=pts.site_id WHERE pts.template_id=t.id),'[]'::jsonb) AS sites`;
export async function createTemplate(input:z.infer<typeof templateInput>,audit:Audit){await writable();const c=await company();if(!c)throw new Error('PLANNING_NOT_CONFIGURED');const row=(await db.query(`INSERT INTO planned_shift_templates(company_id,name,version,status,time_zone,segments,expected_minutes,created_by_user_id) VALUES($1,$2,1,'published',$3,$4,$5,$6) RETURNING ${templateColumns}`,[c.id,input.name,input.timeZone,JSON.stringify(input.segments),expectedMinutes(input.segments),audit.actor.id])).rows[0];await appendAudit({actorType:'user',actorId:audit.actor.id,action:'shift-planning.template.published',resourceType:'planned-shift-template',resourceId:row.id,result:'success',correlationId:audit.correlationId,changes:{name:row.name,version:row.version}});return row;}
export async function createTemplateVersion(id:string,input:z.infer<typeof templateInput>,audit:Audit){await writable();const c=await company();if(!c)throw new Error('PLANNING_NOT_CONFIGURED');const row=(await db.query(`WITH inserted AS (INSERT INTO planned_shift_templates(company_id,name,version,status,time_zone,segments,expected_minutes,created_by_user_id) SELECT source.company_id,source.name,(SELECT COALESCE(MAX(version),0)+1 FROM planned_shift_templates WHERE company_id=source.company_id AND name=source.name),'published',$3,$4,$5,$6 FROM planned_shift_templates source WHERE source.id=$1 AND source.company_id=$2 RETURNING *), copied AS (INSERT INTO planned_shift_template_sites(template_id,site_id,assigned_by_user_id) SELECT inserted.id,pts.site_id,$6 FROM inserted JOIN planned_shift_template_sites pts ON pts.template_id=$1) SELECT id,name,version,status,time_zone AS "timeZone",segments,expected_minutes AS "expectedMinutes" FROM inserted`,[id,c.id,input.timeZone,JSON.stringify(input.segments),expectedMinutes(input.segments),audit.actor.id])).rows[0];if(!row)throw new Error('PLANNING_REFERENCE_NOT_FOUND');await appendAudit({actorType:'user',actorId:audit.actor.id,action:'shift-planning.template.versioned',resourceType:'planned-shift-template',resourceId:row.id,result:'success',correlationId:audit.correlationId,changes:{sourceTemplateId:id,name:row.name,version:row.version}});return row;}
export async function retireTemplate(id:string,audit:Audit){await writable();const c=await company();if(!c)throw new Error('PLANNING_NOT_CONFIGURED');const row=(await db.query(`UPDATE planned_shift_templates SET status='retired' WHERE id=$1 AND company_id=$2 AND status<>'retired' RETURNING ${templateColumns}`,[id,c.id])).rows[0];if(!row)throw new Error('PLANNING_REFERENCE_NOT_FOUND');await appendAudit({actorType:'user',actorId:audit.actor.id,action:'shift-planning.template.retired',resourceType:'planned-shift-template',resourceId:row.id,result:'success',correlationId:audit.correlationId,changes:{name:row.name,version:row.version}});return row;}
export async function setTemplateSites(id:string,siteIds:string[],audit:Audit){await writable();const c=await company();if(!c)throw new Error('PLANNING_NOT_CONFIGURED');const unique=[...new Set(siteIds)];const valid=(await db.query<{count:string}>(`SELECT count(*) FROM sites WHERE company_id=$1 AND is_active AND id=ANY($2::uuid[])`,[c.id,unique])).rows[0];if(Number(valid?.count)!==unique.length)throw new Error('PLANNING_REFERENCE_NOT_FOUND');const template=await db.query(`SELECT id FROM planned_shift_templates WHERE id=$1 AND company_id=$2`,[id,c.id]);if(!template.rowCount)throw new Error('PLANNING_REFERENCE_NOT_FOUND');await db.query('DELETE FROM planned_shift_template_sites WHERE template_id=$1',[id]);for(const siteId of unique)await db.query('INSERT INTO planned_shift_template_sites(template_id,site_id,assigned_by_user_id) VALUES($1,$2,$3)',[id,siteId,audit.actor.id]);await appendAudit({actorType:'user',actorId:audit.actor.id,action:'shift-planning.template.sites.updated',resourceType:'planned-shift-template',resourceId:id,result:'success',correlationId:audit.correlationId,changes:{siteIds:unique}});}
export async function listTemplates(siteIds?:string[]){const c=await company();if(!c)return [];const siteFilter=siteIds?.length?'AND EXISTS(SELECT 1 FROM planned_shift_template_sites pts WHERE pts.template_id=t.id AND pts.site_id=ANY($2::uuid[]))':'';return (await db.query(`SELECT ${templateListColumns} FROM planned_shift_templates t WHERE t.company_id=$1 ${siteFilter} ORDER BY t.name,t.version DESC`,siteIds?.length?[c.id,siteIds]:[c.id])).rows;}
export async function publishAssignment(input:z.infer<typeof assignmentInput>,audit:Audit,allowedSiteIds?:string[]){if(await moduleStatus()!=='active')throw new Error('PLANNING_MODULE_INACTIVE');if(allowedSiteIds && !allowedSiteIds.length)throw new Error('PLANNING_REFERENCE_NOT_FOUND');const scope=allowedSiteIds?' AND em.site_id=ANY($9::uuid[])':'';const values=[input.employmentId,input.templateId,input.effectiveFrom,input.effectiveTo??null,input.reasonCode,audit.actor.id,audit.correlationId,config.ENVIRONMENT_ID,...(allowedSiteIds?[allowedSiteIds]:[])];const row=(await db.query(`INSERT INTO planned_shift_assignments(company_id,employment_id,site_id,template_id,template_snapshot,effective_from,effective_to,status,reason_code,created_by_user_id,published_by_user_id,published_at,correlation_id) SELECT c.id,em.id,em.site_id,t.id,jsonb_build_object('name',t.name,'version',t.version,'timeZone',t.time_zone,'segments',t.segments,'expectedMinutes',t.expected_minutes),$3,$4,'published',$5,$6,$6,clock_timestamp(),$7 FROM employments em JOIN employees e ON e.id=em.employee_id JOIN companies c ON c.id=e.company_id JOIN planned_shift_templates t ON t.id=$2 AND t.company_id=c.id AND t.status='published' JOIN planned_shift_template_sites pts ON pts.template_id=t.id AND pts.site_id=em.site_id WHERE em.id=$1 AND c.environment_id=$8 ${scope} AND e.is_active AND em.effective_from<=$3::date AND (em.effective_to IS NULL OR em.effective_to>$3::date) AND $3::date>CURRENT_DATE RETURNING id,employment_id AS "employmentId",site_id AS "siteId",template_id AS "templateId",effective_from::text AS "effectiveFrom",effective_to::text AS "effectiveTo",status`,values)).rows[0];if(!row)throw new Error('PLANNING_REFERENCE_NOT_FOUND');await appendAudit({actorType:'user',actorId:audit.actor.id,action:'shift-planning.assignment.published',resourceType:'planned-shift-assignment',resourceId:row.id,result:'success',correlationId:audit.correlationId,changes:{employmentId:row.employmentId,siteId:row.siteId,effectiveFrom:row.effectiveFrom,effectiveTo:row.effectiveTo}});return row;}
export async function listAssignments(){const c=await company();if(!c)return [];return (await db.query(`SELECT id,employment_id AS "employmentId",site_id AS "siteId",template_id AS "templateId",effective_from::text AS "effectiveFrom",effective_to::text AS "effectiveTo",status FROM planned_shift_assignments WHERE company_id=$1 ORDER BY effective_from`,[c.id])).rows;}
