import { db } from '@/shared/db';
import { config } from '@/shared/config';
import { appendAudit } from '@/audit/audit-writer';
import type { ScopedActor } from '@/permissions/authorizer';
import type { ShiftPlanningModuleStatus } from './contracts';
import type { z } from 'zod';
import type { assignmentInput, moduleStatusInput, templateInput } from './validation';

type Audit = { actor: ScopedActor; correlationId: string };
const company = async () => (await db.query<{id:string}>('SELECT id FROM companies WHERE environment_id=$1 AND is_active',[config.ENVIRONMENT_ID])).rows[0] ?? null;

export async function moduleStatus(): Promise<ShiftPlanningModuleStatus> { const row=await db.query<{status:ShiftPlanningModuleStatus}>('SELECT cm.status FROM company_modules cm JOIN companies c ON c.id=cm.company_id WHERE c.environment_id=$1 AND cm.module_key=$2',[config.ENVIRONMENT_ID,'shift_planning']); return row.rows[0]?.status ?? 'disabled'; }
export async function setModuleStatus(input:z.infer<typeof moduleStatusInput>,audit:Audit){const c=await company();if(!c)throw new Error('PLANNING_NOT_CONFIGURED');const row=(await db.query<{status:ShiftPlanningModuleStatus}>(`INSERT INTO company_modules(company_id,module_key,status,updated_by_user_id) VALUES($1,'shift_planning',$2,$3) ON CONFLICT(company_id,module_key) DO UPDATE SET status=EXCLUDED.status,version=company_modules.version+1,updated_by_user_id=EXCLUDED.updated_by_user_id,updated_at=clock_timestamp() RETURNING status`,[c.id,input.status,audit.actor.id])).rows[0];await appendAudit({actorType:'user',actorId:audit.actor.id,action:'shift-planning.module.updated',resourceType:'company-module',resourceId:c.id,result:'success',correlationId:audit.correlationId,changes:{module:'shift_planning',status:row.status}});return row;}
const writable = async () => { const status=await moduleStatus(); if(status==='disabled'||status==='paused')throw new Error('PLANNING_MODULE_INACTIVE'); return status; };
export async function createTemplate(input:z.infer<typeof templateInput>,audit:Audit){await writable();const c=await company();if(!c)throw new Error('PLANNING_NOT_CONFIGURED');const row=(await db.query(`INSERT INTO planned_shift_templates(company_id,name,version,status,time_zone,segments,expected_minutes,created_by_user_id) VALUES($1,$2,1,'published',$3,$4,$5,$6) RETURNING id,name,version,status,time_zone AS "timeZone",segments,expected_minutes AS "expectedMinutes"`,[c.id,input.name,input.timeZone,JSON.stringify(input.segments),input.expectedMinutes,audit.actor.id])).rows[0];await appendAudit({actorType:'user',actorId:audit.actor.id,action:'shift-planning.template.published',resourceType:'planned-shift-template',resourceId:row.id,result:'success',correlationId:audit.correlationId,changes:{name:row.name,version:row.version}});return row;}
export async function publishAssignment(input:z.infer<typeof assignmentInput>,audit:Audit){if(await moduleStatus()!=='active')throw new Error('PLANNING_MODULE_INACTIVE');const row=(await db.query(`INSERT INTO planned_shift_assignments(company_id,employment_id,site_id,template_id,template_snapshot,effective_from,effective_to,status,reason_code,created_by_user_id,published_by_user_id,published_at,correlation_id) SELECT c.id,em.id,em.site_id,t.id,jsonb_build_object('name',t.name,'version',t.version,'timeZone',t.time_zone,'segments',t.segments,'expectedMinutes',t.expected_minutes),$3,$4,'published',$5,$6,$6, $7 FROM employments em JOIN employees e ON e.id=em.employee_id JOIN companies c ON c.id=e.company_id JOIN planned_shift_templates t ON t.id=$2 AND t.company_id=c.id AND t.status='published' WHERE em.id=$1 AND c.environment_id=$8 AND e.is_active AND em.effective_from<=$3::date AND (em.effective_to IS NULL OR em.effective_to>$3::date) AND $3::date>CURRENT_DATE RETURNING id,employment_id AS "employmentId",site_id AS "siteId",template_id AS "templateId",effective_from::text AS "effectiveFrom",effective_to::text AS "effectiveTo",status`,[input.employmentId,input.templateId,input.effectiveFrom,input.effectiveTo??null,input.reasonCode,audit.actor.id,audit.correlationId,config.ENVIRONMENT_ID])).rows[0];if(!row)throw new Error('PLANNING_REFERENCE_NOT_FOUND');await appendAudit({actorType:'user',actorId:audit.actor.id,action:'shift-planning.assignment.published',resourceType:'planned-shift-assignment',resourceId:row.id,result:'success',correlationId:audit.correlationId,changes:{employmentId:row.employmentId,siteId:row.siteId,effectiveFrom:row.effectiveFrom,effectiveTo:row.effectiveTo}});return row;}
