import { db } from '@/shared/db';
import { config } from '@/shared/config';
import { appendAudit } from '@/audit/audit-writer';
import type { ClockingPolicyMethod, EffectiveClockingPolicy } from './contracts';

const zoneColumns='z.id,z.label,z.latitude::float8 AS latitude,z.longitude::float8 AS longitude,z.radius_meters AS "radiusMeters"';
const policyColumns='p.id,p.employment_id AS "employmentId",p.method,p.location_zone_id AS "locationZoneId",p.reason_code AS "reasonCode",p.effective_from::text AS "effectiveFrom",p.effective_to::text AS "effectiveTo",z.label AS "zoneLabel"';
export async function listZones(){return (await db.query(`SELECT ${zoneColumns} FROM work_location_zones z JOIN companies c ON c.id=z.company_id WHERE c.environment_id=$1 AND z.is_active ORDER BY z.label`,[config.ENVIRONMENT_ID])).rows;}
export async function createZone(input:{label:string;latitude:number;longitude:number;radiusMeters:number},userId:string,correlationId:string){const zone=(await db.query(`INSERT INTO work_location_zones(company_id,label,latitude,longitude,radius_meters,created_by_user_id) SELECT id,$2,$3,$4,$5,$6 FROM companies WHERE environment_id=$1 AND is_active RETURNING id,label,latitude::float8 AS latitude,longitude::float8 AS longitude,radius_meters AS "radiusMeters"`,[config.ENVIRONMENT_ID,input.label,input.latitude,input.longitude,input.radiusMeters,userId])).rows[0]??null;if(zone)await appendAudit({actorType:'user',actorId:userId,action:'clocking-policy.zone.created',resourceType:'work-location-zone',resourceId:zone.id,result:'success',correlationId,changes:{label:zone.label,radiusMeters:zone.radiusMeters}});return zone;}
export async function listPolicies(){return (await db.query(`SELECT ${policyColumns} FROM employment_clocking_policies p JOIN employments em ON em.id=p.employment_id JOIN employees e ON e.id=em.employee_id JOIN companies c ON c.id=e.company_id LEFT JOIN work_location_zones z ON z.id=p.location_zone_id WHERE c.environment_id=$1 ORDER BY p.effective_from DESC,p.created_at DESC`,[config.ENVIRONMENT_ID])).rows;}
export async function createPolicy(input:{employmentId:string;method:ClockingPolicyMethod;locationZoneId:string|null;reasonCode:'fixed_site'|'approved_mobility';effectiveFrom:string;effectiveTo?:string|null},userId:string,correlationId:string){const result=await db.query(`INSERT INTO employment_clocking_policies(employment_id,method,location_zone_id,reason_code,effective_from,effective_to,created_by_user_id) SELECT em.id,$2,$3,$4,$5,$6,$7 FROM employments em JOIN employees e ON e.id=em.employee_id JOIN companies c ON c.id=e.company_id LEFT JOIN work_location_zones z ON z.id=$3 AND z.company_id=c.id AND z.is_active WHERE em.id=$1 AND c.environment_id=$8 AND ($2='web' OR z.id IS NOT NULL) RETURNING id`,[input.employmentId,input.method,input.locationZoneId,input.reasonCode,input.effectiveFrom,input.effectiveTo??null,userId,config.ENVIRONMENT_ID]);if(!result.rowCount)return null;const policy=(await db.query(`SELECT ${policyColumns} FROM employment_clocking_policies p LEFT JOIN work_location_zones z ON z.id=p.location_zone_id WHERE p.id=$1`,[result.rows[0].id])).rows[0];await appendAudit({actorType:'user',actorId:userId,action:'clocking-policy.assigned',resourceType:'employment-clocking-policy',resourceId:policy.id,result:'success',correlationId,changes:{employmentId:policy.employmentId,method:policy.method,locationZoneId:policy.locationZoneId??null,reasonCode:policy.reasonCode,effectiveFrom:policy.effectiveFrom,effectiveTo:policy.effectiveTo??null}});return policy;}
export async function effectivePolicy(employmentId:string,laborDate:string):Promise<EffectiveClockingPolicy>{const row=(await db.query<{id:string;method:ClockingPolicyMethod;zoneLabel:string|null}>(`SELECT p.id,p.method,z.label AS "zoneLabel" FROM employment_clocking_policies p LEFT JOIN work_location_zones z ON z.id=p.location_zone_id WHERE p.employment_id=$1 AND p.effective_from<=$2::date AND (p.effective_to IS NULL OR p.effective_to>$2::date) ORDER BY p.effective_from DESC LIMIT 1`,[employmentId,laborDate])).rows[0];return row?.method==='geo_punctual'?{method:'geo_punctual',policyId:row.id,zoneLabel:row.zoneLabel??undefined,requiresPunctualLocation:true}:{method:'web',requiresPunctualLocation:false};}
export async function effectivePolicyForEmployee(employeeId:string):Promise<EffectiveClockingPolicy>{const row=(await db.query<{employmentId:string;laborDate:string}>(`SELECT em.id AS "employmentId",(clock_timestamp() AT TIME ZONE s.time_zone)::date::text AS "laborDate" FROM employments em JOIN employees e ON e.id=em.employee_id JOIN companies c ON c.id=e.company_id JOIN sites s ON s.id=em.site_id WHERE em.employee_id=$1 AND e.is_active AND c.environment_id=$2 AND em.effective_from<=(clock_timestamp() AT TIME ZONE s.time_zone)::date AND (em.effective_to IS NULL OR em.effective_to>(clock_timestamp() AT TIME ZONE s.time_zone)::date) ORDER BY em.effective_from DESC LIMIT 1`,[employeeId,config.ENVIRONMENT_ID])).rows[0];return row?effectivePolicy(row.employmentId,row.laborDate):{method:'web',requiresPunctualLocation:false};}
export async function activeGeoPolicy(employmentId:string,laborDate:string){return (await db.query<{id:string;zoneId:string;latitude:number;longitude:number;radiusMeters:number}>(`SELECT p.id,z.id AS "zoneId",z.latitude::float8 AS latitude,z.longitude::float8 AS longitude,z.radius_meters AS "radiusMeters" FROM employment_clocking_policies p JOIN work_location_zones z ON z.id=p.location_zone_id AND z.is_active WHERE p.employment_id=$1 AND p.method='geo_punctual' AND p.effective_from<=$2::date AND (p.effective_to IS NULL OR p.effective_to>$2::date) ORDER BY p.effective_from DESC LIMIT 1`,[employmentId,laborDate])).rows[0]??null;}
