import { describe,expect,it } from 'vitest';
import { priorMonths,summarize } from '../src/monthly-review/contracts';
import { readFileSync } from 'node:fs';
const service=readFileSync('src/monthly-review/service.ts','utf8');
const route=readFileSync('src/app/api/v1/monthly-reviews/me/route.ts','utf8');
const component=readFileSync('src/monthly-review/components.tsx','utf8');
const migration=readFileSync('migrations/s040_202609211900_monthly_reviews.sql','utf8');
const styles=readFileSync('src/app/globals.css','utf8');
describe('revisión mensual informativa',()=>{it('limita los períodos a doce meses cerrados',()=>{expect(priorMonths('2026-09')).toEqual(['2026-08','2026-07','2026-06','2026-05','2026-04','2026-03','2026-02','2026-01','2025-12','2025-11','2025-10','2025-09']);});it('resume sin confundir valores ausentes con cero',()=>{const result=summarize([{laborDate:'2026-08-01',expectedMinutes:null,effectiveMinutes:null,differenceMinutes:null,incidents:0,pendingCorrections:0,holiday:'national',leave:null},{laborDate:'2026-08-02',expectedMinutes:480,effectiveMinutes:450,differenceMinutes:-30,incidents:1,pendingCorrections:1,holiday:null,leave:null}]);expect(result).toMatchObject({calculatedDays:1,expectedMinutes:480,effectiveMinutes:450,differenceMinutes:-30,incidentDays:1,pendingCorrections:1});});it('mantiene lectura propia, marca idempotente y recálculo derivado',()=>{expect(service).toContain("assertAuthorized(actor,'time-calculation.read:self')");expect(service).toContain("assertAuthorized(actor,'monthly-review.create:self')");expect(service).toContain('snapshotHash!==current.snapshotHash');expect(service).toContain('pg_advisory_xact_lock');expect(route).toContain("'idempotency-key'");expect(migration).toContain('CREATE TABLE IF NOT EXISTS monthly_period_reviews');expect(migration).toContain('UNIQUE(employee_id,idempotency_key)');});it('ofrece estados y alternativa móvil accesibles',()=>{expect(component).toContain('Requiere nueva revisión');expect(component).toContain('aria-live="polite"');expect(component).toContain('monthly-review__mobile');expect(styles).toContain('@media(max-width:540px){.monthly-review__heading');});});
