import { createHash } from 'node:crypto';
import type pg from 'pg';
import { appendAudit } from '@/audit/audit-writer';
import { db } from '@/shared/db';
import { config } from '@/shared/config';
import { assertAuthorized, assertSiteScope, type ScopedActor } from '@/permissions/authorizer';
import { employeeForUser } from '@/time-events/service';
import type { LeaveRequest,LeaveRequestCategory } from './contracts';

type Row={id:string;employeeId:string;siteId:string;fromDate:string;toDate:string;category:LeaveRequestCategory;comment:string|null;status:LeaveRequest['status'];requestedAt:Date;decision:string|null;decisionKey:string|null;decidedAt:Date|null;cancelledAt:Date|null};
const cols=`r.id,r.employee_id AS "employeeId",r.site_id AS "siteId",r.from_date::text AS "fromDate",r.to_date::text AS "toDate",r.category,r.request_comment AS comment,r.status,r.requested_at AS "requestedAt",d.decision,d.idempotency_key AS "decisionKey",d.decided_at AS "decidedAt",r.cancelled_at AS "cancelledAt"`;
const map=(r:Row):LeaveRequest=>({id:r.id,employeeId:r.employeeId,siteId:r.siteId,fromDate:r.fromDate,toDate:r.toDate,category:r.category,comment:r.comment,status:r.status,requestedAt:r.requestedAt.toISOString(),decision:r.decision?{decision:r.decision as 'approved'|'rejected',decidedAt:r.decidedAt!.toISOString()}:null,cancelledAt:r.cancelledAt?.toISOString()??null});
const fingerprint=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
async function one(client:pg.Pool|pg.PoolClient,id:string){return (await client.query<Row>(`SELECT ${cols} FROM leave_requests r LEFT JOIN leave_request_decisions d ON d.leave_request_id=r.id WHERE r.id=$1`,[id])).rows[0]??null;}
async function userForEmployee(employeeId:string){return (await db.query<{userId:string}>(`SELECT e.user_id AS "userId" FROM employees e JOIN companies c ON c.id=e.company_id WHERE e.id=$1 AND e.is_active AND c.environment_id=$2`,[employeeId,config.ENVIRONMENT_ID])).rows[0]?.userId??null;}
async function activeEmployment(client:pg.PoolClient,employeeId:string,fromDate:string,toDate:string){return (await client.query<{siteId:string}>(`SELECT em.site_id AS "siteId" FROM employments em JOIN employees e ON e.id=em.employee_id JOIN companies c ON c.id=e.company_id WHERE em.employee_id=$1 AND e.is_active AND c.is_active AND c.environment_id=$2 AND em.effective_from<=$3::date AND (em.effective_to IS NULL OR em.effective_to>$4::date) ORDER BY em.effective_from DESC LIMIT 1`,[employeeId,config.ENVIRONMENT_ID,fromDate,toDate])).rows[0]??null;}

export async function createLeaveRequest(actor:ScopedActor,input:{fromDate:string;toDate:string;category:LeaveRequestCategory;comment?:string},key:string,cid:string){
  assertAuthorized(actor,'leave-request.create:self');const employeeId=await employeeForUser(actor.id);if(!employeeId)throw new Error('LEAVE_REQUEST_NOT_OWN');const client=await db.connect();try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1, 2401))',[employeeId]);const f=fingerprint(input);const prior=await client.query<{request_fingerprint:string;response:{leaveRequest:LeaveRequest}}>('SELECT request_fingerprint,response FROM leave_request_idempotency WHERE employee_id=$1 AND idempotency_key=$2',[employeeId,key]);if(prior.rowCount){if(prior.rows[0].request_fingerprint!==f)throw new Error('IDEMPOTENCY_CONFLICT');await client.query('COMMIT');return {...prior.rows[0].response,replayed:true};}const employment=await activeEmployment(client,employeeId,input.fromDate,input.toDate);if(!employment)throw new Error('LEAVE_EMPLOYMENT_NOT_ACTIVE');const created=(await client.query<Row>(`INSERT INTO leave_requests(employee_id,site_id,from_date,to_date,category,request_comment,requested_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,employee_id AS "employeeId",site_id AS "siteId",from_date::text AS "fromDate",to_date::text AS "toDate",category,request_comment AS comment,status,requested_at AS "requestedAt",NULL::text AS decision,NULL::text AS "decisionKey",NULL::timestamptz AS "decidedAt",NULL::timestamptz AS "cancelledAt"`,[employeeId,employment.siteId,input.fromDate,input.toDate,input.category,input.comment??null,actor.id])).rows[0];const leaveRequest=map(created);await client.query('INSERT INTO leave_request_idempotency(employee_id,idempotency_key,request_fingerprint,leave_request_id,response) VALUES($1,$2,$3,$4,$5)',[employeeId,key,f,created.id,JSON.stringify({leaveRequest})]);await client.query('INSERT INTO domain_event_outbox(name,payload,correlation_id) VALUES($1,$2,$3)',['leave-request.requested',JSON.stringify({leaveRequestId:created.id,employeeId,siteId:employment.siteId,fromDate:input.fromDate,toDate:input.toDate,category:input.category}),cid]);await appendAudit({actorType:'user',actorId:actor.id,action:'leave-request.requested',resourceType:'leave-request',resourceId:created.id,result:'success',correlationId:cid,changes:{employeeId,siteId:employment.siteId,fromDate:input.fromDate,toDate:input.toDate,category:input.category,hasComment:!!input.comment}});await client.query('COMMIT');return {leaveRequest,replayed:false};}catch(e){await client.query('ROLLBACK').catch(()=>undefined);throw e;}finally{client.release();}
}
export async function listLeaveRequests(actor:ScopedActor,mine:boolean){if(mine)assertAuthorized(actor,'leave-request.read:self');else assertAuthorized(actor,'leave-request.read:scope');const own=mine?await employeeForUser(actor.id):null;const rows=(await db.query<Row>(`SELECT ${cols} FROM leave_requests r LEFT JOIN leave_request_decisions d ON d.leave_request_id=r.id ${mine?'WHERE r.employee_id=$1':''} ORDER BY r.requested_at DESC`,mine?[own]:[])).rows;const values=rows.map(map);for(const item of values)if(!mine)assertSiteScope(actor,item.siteId);return values;}
export async function decideLeaveRequest(actor:ScopedActor,id:string,input:{decision:'approved'|'rejected'},key:string,cid:string){assertAuthorized(actor,'leave-request.decide:scope');const client=await db.connect();try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1, 2402))',[id]);const current=await one(client,id);if(!current)throw new Error('LEAVE_REQUEST_NOT_FOUND');assertSiteScope(actor,current.siteId);const f=fingerprint(input);if(current.status!=='pending'){if(current.decisionKey===key&&current.decision===input.decision){await client.query('COMMIT');return {leaveRequest:map(current),replayed:true};}if(current.decisionKey===key)throw new Error('IDEMPOTENCY_CONFLICT');throw new Error('LEAVE_REQUEST_STATE_INVALID');}const decision=(await client.query<{id:string}>(`INSERT INTO leave_request_decisions(leave_request_id,decision,idempotency_key,request_fingerprint,decided_by_user_id) VALUES($1,$2,$3,$4,$5) RETURNING id`,[id,input.decision,key,f,actor.id])).rows[0];await client.query('UPDATE leave_requests SET status=$2,decision_id=$3 WHERE id=$1',[id,input.decision,decision.id]);await client.query('INSERT INTO domain_event_outbox(name,payload,correlation_id) VALUES($1,$2,$3)',['leave-request.decided',JSON.stringify({leaveRequestId:id,decision:input.decision,employeeId:current.employeeId,siteId:current.siteId}),cid]);await appendAudit({actorType:'user',actorId:actor.id,action:`leave-request.${input.decision}`,resourceType:'leave-request',resourceId:id,result:'success',correlationId:cid,changes:{employeeId:current.employeeId,siteId:current.siteId,fromDate:current.fromDate,toDate:current.toDate}});const updated=await one(client,id);await client.query('COMMIT');return {leaveRequest:map(updated!),replayed:false};}catch(e){await client.query('ROLLBACK').catch(()=>undefined);throw e;}finally{client.release();}}
export async function cancelLeaveRequest(actor:ScopedActor,id:string,cid:string){assertAuthorized(actor,'leave-request.cancel:self');const client=await db.connect();try{await client.query('BEGIN');const current=await one(client,id);if(!current)throw new Error('LEAVE_REQUEST_NOT_FOUND');if(actor.id!==await userForEmployee(current.employeeId))throw new Error('LEAVE_REQUEST_NOT_OWN');if(current.status!=='pending')throw new Error('LEAVE_REQUEST_STATE_INVALID');await client.query('UPDATE leave_requests SET status=\'cancelled\',cancelled_by_user_id=$2,cancelled_at=clock_timestamp() WHERE id=$1',[id,actor.id]);await client.query('INSERT INTO domain_event_outbox(name,payload,correlation_id) VALUES($1,$2,$3)',['leave-request.cancelled',JSON.stringify({leaveRequestId:id,employeeId:current.employeeId,siteId:current.siteId}),cid]);await appendAudit({actorType:'user',actorId:actor.id,action:'leave-request.cancelled',resourceType:'leave-request',resourceId:id,result:'success',correlationId:cid,changes:{employeeId:current.employeeId,siteId:current.siteId}});const updated=await one(client,id);await client.query('COMMIT');return map(updated!);}catch(e){await client.query('ROLLBACK').catch(()=>undefined);throw e;}finally{client.release();}}
