'use client';

import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { AdminNav } from '@/admin/components';
import { LoadingBlock, StatusBadge, StatusNotice } from '@/ui/feedback';
import { configurationApi as api, type Calendar, type Company, type Employee, type Employment, type RuleVersion, type Shift, type Site, type WorkRule } from './api';

type Data = { company?: Company; sites: Site[]; employees: Employee[]; employments: Employment[]; calendars: Calendar[]; shifts: Shift[]; rules: WorkRule[]; versions: RuleVersion[] };
const empty: Data = { sites: [], employees: [], employments: [], calendars: [], shifts: [], rules: [], versions: [] };
const today = () => new Date().toISOString().slice(0, 10);
const fail = (value: unknown) => value instanceof Error ? value.message : 'No se pudo completar la operación.';

function ConfigurationForm({ title, children, onSubmit, busy }: { title: string; children: ReactNode; onSubmit: (form: FormData) => Promise<void>; busy: boolean }) {
  return <section className="configuration-card"><h2>{title}</h2><form className="configuration-form" onSubmit={(event) => { event.preventDefault(); void onSubmit(new FormData(event.currentTarget)); }}>{children}<button disabled={busy}>{busy ? 'Guardando…' : 'Guardar configuración'}</button></form></section>;
}

function Select({ label, name, items, required = false }: { label: string; name: string; items: Array<{ id: string; name?: string; displayName?: string }>; required?: boolean }) {
  return <label>{label}<select name={name} required={required}><option value="">{required ? 'Seleccione una opción' : 'Sin asignar'}</option>{items.map((item) => <option key={item.id} value={item.id}>{item.name ?? item.displayName ?? item.id}</option>)}</select></label>;
}

function progress(data: Data) {
  return [{ label: 'Empresa', ready: !!data.company }, { label: 'Centro', ready: data.sites.length > 0 }, { label: 'Persona', ready: data.employees.length > 0 }, { label: 'Relación activa', ready: data.employments.length > 0 }, { label: 'Calendario', ready: data.calendars.length > 0 }, { label: 'Regla y vigencia', ready: data.rules.length > 0 && data.versions.length > 0 }];
}

export function Configuration() {
  const [data, setData] = useState<Data>(empty); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string>(); const [error, setError] = useState<string>(); const [ruleScope, setRuleScope] = useState<'company' | 'site'>('company');
  const load = useCallback(async () => { setLoading(true); try { const [company, sites, employees, employments, calendars, shifts, rules, versions] = await Promise.all([api.company(), api.sites(), api.employees(), api.employments(), api.calendars(), api.shifts(), api.rules(), api.versions()]); setData({ company, sites, employees, employments, calendars, shifts, rules, versions }); setError(undefined); } catch (value) { setError(fail(value)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const submit = (action: (form: FormData) => Promise<unknown>) => async (form: FormData) => { setBusy(true); setError(undefined); setMessage(undefined); try { await action(form); await load(); setMessage('Configuración confirmada por el servidor y registrada en la auditoría existente.'); } catch (value) { setError(fail(value)); } finally { setBusy(false); } };
  const checklist = progress(data); const ready = checklist.filter((item) => item.ready).length; const scopeItems = ruleScope === 'company' ? (data.company ? [data.company] : []) : data.sites;
  return <main className="admin-shell"><AdminNav /><header className="configuration-header"><p className="eyebrow">CONFIGURACIÓN DEL PILOTO</p><h1>Configuración guiada</h1><p className="subtle">Prepare los datos mínimos antes de invitar al equipo. El servidor valida cada cambio; revise calendario y regla con su asesoría: esta pantalla no interpreta convenios ni garantiza cumplimiento automático.</p></header>
    {loading && <LoadingBlock />}{error && <StatusNotice kind="error">{error}</StatusNotice>}{message && <StatusNotice kind="success">{message}</StatusNotice>}
    <section className="configuration-overview" aria-labelledby="configuration-progress"><div><p className="eyebrow">ESTADO DEL ENTORNO</p><h2 id="configuration-progress">{ready} de {checklist.length} pasos confirmados</h2><p className="subtle">El progreso se calcula sólo a partir de datos confirmados por API.</p></div><ul className="configuration-checklist">{checklist.map((item) => <li key={item.label}><span>{item.label}</span><StatusBadge kind={item.ready ? 'success' : 'warning'}>{item.ready ? 'Confirmado' : 'Pendiente'}</StatusBadge></li>)}</ul></section>
    <section className="configuration-group"><header><p className="eyebrow">ORGANIZACIÓN</p><h2>Base del entorno</h2></header><div className="configuration-grid">
      <ConfigurationForm title="1. Empresa" busy={busy} onSubmit={submit((form) => { const input = { name: String(form.get('name')).trim(), legalIdentifier: String(form.get('legalIdentifier')).trim() || null }; return data.company ? api.saveCompany(input) : api.createCompany(input); })}><label>Nombre<input name="name" required maxLength={160} defaultValue={data.company?.name ?? ''} /></label><label>Identificador legal opcional<input name="legalIdentifier" maxLength={32} defaultValue={data.company?.legalIdentifier ?? ''} /></label></ConfigurationForm>
      <ConfigurationForm title="2. Centro" busy={busy} onSubmit={submit((form) => api.createSite({ name: String(form.get('name')).trim(), timeZone: String(form.get('timeZone')) }))}><label>Nombre<input name="name" required maxLength={160} /></label><label>Zona horaria IANA<input name="timeZone" required defaultValue="Europe/Madrid" aria-describedby="zone-help" /><span id="zone-help" className="field-help">Ejemplo: Europe/Madrid. El servidor valida la zona.</span></label></ConfigurationForm>
    </div></section>
    <section className="configuration-group"><header><p className="eyebrow">EQUIPO</p><h2>Personas y ámbito</h2></header><div className="configuration-grid">
      <ConfigurationForm title="3. Persona" busy={busy} onSubmit={submit((form) => api.createEmployee({ displayName: String(form.get('displayName')).trim() }))}><label>Nombre visible<input name="displayName" required maxLength={160} /></label><p className="field-help">No se solicita información personal no necesaria ni se crea una cuenta de acceso desde este formulario.</p></ConfigurationForm>
      <ConfigurationForm title="4. Relación laboral" busy={busy} onSubmit={submit((form) => api.createEmployment({ employeeId: String(form.get('employeeId')), siteId: String(form.get('siteId')), managerEmployeeId: String(form.get('managerEmployeeId')) || null, effectiveFrom: String(form.get('effectiveFrom')), effectiveTo: String(form.get('effectiveTo')) || null }))}><Select label="Persona" name="employeeId" items={data.employees} required /><Select label="Centro" name="siteId" items={data.sites} required /><Select label="Responsable opcional" name="managerEmployeeId" items={data.employees} /><label>Vigente desde<input name="effectiveFrom" type="date" required defaultValue={today()} /></label><label>Vigente hasta (opcional)<input name="effectiveTo" type="date" /></label></ConfigurationForm>
    </div></section>
    <section className="configuration-group"><header><p className="eyebrow">JORNADA</p><h2>Calendario, regla y vigencia</h2></header><div className="configuration-grid">
      <ConfigurationForm title="5. Calendario" busy={busy} onSubmit={submit((form) => api.createCalendar({ name: String(form.get('name')).trim(), timeZone: String(form.get('timeZone')), workingDays: [1, 2, 3, 4, 5], holidays: [] }))}><label>Nombre<input name="name" required maxLength={160} /></label><label>Zona horaria IANA<input name="timeZone" required defaultValue="Europe/Madrid" /></label><p className="field-help">Crea un calendario laborable de lunes a viernes sin festivos. Los ajustes futuros requieren una nueva configuración; no reescriben una versión publicada.</p></ConfigurationForm>
      <ConfigurationForm title="6. Turno opcional" busy={busy} onSubmit={submit((form) => api.createShift({ name: String(form.get('name')).trim(), segments: String(form.get('segments')).split(',').map((segment) => { const [start, end] = segment.trim().split('-'); return { start, end }; }) }))}><label>Nombre<input name="name" required maxLength={160} /></label><label>Tramos HH:mm-HH:mm, separados por comas<input name="segments" required placeholder="09:00-13:00, 14:00-18:00" /></label></ConfigurationForm>
      <ConfigurationForm title="7. Regla" busy={busy} onSubmit={submit((form) => api.createRule({ name: String(form.get('name')).trim(), scopeType: String(form.get('scopeType')) as 'company' | 'site', scopeId: String(form.get('scopeId')) }))}><label>Nombre<input name="name" required maxLength={160} /></label><label>Ámbito<select name="scopeType" value={ruleScope} onChange={(event) => setRuleScope(event.target.value as 'company' | 'site')}><option value="company">Empresa</option><option value="site">Centro</option></select></label><Select label={ruleScope === 'company' ? 'Empresa' : 'Centro'} name="scopeId" items={scopeItems} required /></ConfigurationForm>
      <ConfigurationForm title="8. Versión vigente de regla" busy={busy} onSubmit={submit((form) => api.createVersion({ workRuleId: String(form.get('workRuleId')), effectiveFrom: String(form.get('effectiveFrom')), effectiveTo: String(form.get('effectiveTo')) || null, timeZone: String(form.get('timeZone')), expectedMinutes: Number(form.get('expectedMinutes')), pausePolicy: { mode: 'manual_visible', autoDeduct: false }, calendarId: String(form.get('calendarId')) || null, shiftId: String(form.get('shiftId')) || null }))}><Select label="Regla" name="workRuleId" items={data.rules} required /><label>Vigente desde<input name="effectiveFrom" type="date" required defaultValue={today()} /></label><label>Vigente hasta (opcional)<input name="effectiveTo" type="date" /></label><label>Zona horaria IANA<input name="timeZone" required defaultValue="Europe/Madrid" /></label><label>Minutos esperados<input name="expectedMinutes" type="number" min="0" max="1440" required defaultValue="480" /></label><Select label="Calendario opcional" name="calendarId" items={data.calendars} /><Select label="Turno opcional" name="shiftId" items={data.shifts} /><p className="field-help">Las pausas son manuales y visibles; no se descuenta tiempo automáticamente. Publicar una nueva versión no permite sobrescribir la historia.</p></ConfigurationForm>
    </div></section>
    <section className="configuration-export"><div><p className="eyebrow">EXPORTACIONES</p><h2>Aún no disponibles</h2></div><StatusNotice kind="warning">La solicitud y descarga visible permanecen bloqueadas hasta que S15 cierre y evidencie el almacenamiento aislado, vencimiento, borrado controlado y auditoría. No hay enlaces públicos.</StatusNotice></section>
  </main>;
}
