import { OFFICIAL_HOLIDAY_SOURCES } from './catalog';

export type ImportedHoliday={date:string;label:string;type:'local';locality:string};
const clean=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLocaleLowerCase('es');
const months:Record<string,string>={enero:'01',febrero:'02',marzo:'03',abril:'04',mayo:'05',junio:'06',julio:'07',agosto:'08',septiembre:'09',octubre:'10',noviembre:'11',diciembre:'12'};

export function parseCatalunya(rows:unknown,locality:string,year:number):ImportedHoliday[]{if(!Array.isArray(rows))return [];return rows.flatMap((row)=>{const item=row as Record<string,unknown>;const date=String(item.data??'').slice(0,10);if(String(item.any_calendari)!==String(year)||clean(String(item.ajuntament_o_nucli_municipal??''))!==clean(locality)||!/^\d{4}-\d{2}-\d{2}$/.test(date))return [];return [{date,label:String(item.festiu??'Festivo local'),type:'local' as const,locality:String(item.ajuntament_o_nucli_municipal)}];});}
export function parseCastellon(rows:unknown,locality:string,year:number):ImportedHoliday[]{if(!Array.isArray(rows))return [];return rows.flatMap((row)=>{const item=row as Record<string,unknown>;const [day,monthName]=String(item.fecha??'').toLocaleLowerCase('es').match(/^(\d{1,2})\s+de\s+([a-záéíóú]+)$/)?.slice(1)??[];const month=months[monthName];if(clean(String(item.localidad??''))!==clean(locality)||!month)return [];return [{date:`${year}-${month}-${day.padStart(2,'0')}`,label:String(item.festividad??'Festivo local'),type:'local' as const,locality:String(item.localidad)}];});}
export async function previewOfficialHolidays(sourceId:string,locality:string,year:number){const source=OFFICIAL_HOLIDAY_SOURCES.find(item=>item.id===sourceId);if(!source)throw new Error('HOLIDAY_SOURCE_NOT_FOUND');if(source.adapter==='catalogue')throw new Error('HOLIDAY_SOURCE_NOT_READY');const response=await fetch(source.url,{headers:{accept:'application/json'},signal:AbortSignal.timeout(20_000)});if(!response.ok)throw new Error('HOLIDAY_SOURCE_UNAVAILABLE');const payload:unknown=await response.json();const holidays=source.adapter==='catalunya'?parseCatalunya(payload,locality,year):parseCastellon(payload,locality,year);return {source:{id:source.id,name:source.name,publisher:source.publisher,url:source.url},holidays};}
