import { db } from '@/shared/db';
import { appendAudit } from '@/audit/audit-writer';
import { assertIana, date, segments } from './validation';
import { z } from 'zod';

const pausePolicy = z.object({ mode:z.literal('manual_visible'), autoDeduct:z.literal(false), minimumMinutes:z.number().int().min(0).max(1440).optional() });
export const versionShape=z.object({ effectiveFrom:date, effectiveTo:date.nullable().optional(), timeZone:z.string().min(1), expectedMinutes:z.number().int().min(0).max(1440), pausePolicy, calendarId:z.string().uuid().nullable().optional(), shiftId:z.string().uuid().nullable().optional() });
const versionInput=versionShape.superRefine((v,ctx)=>{if(v.effectiveTo && v.effectiveTo<=v.effectiveFrom)ctx.addIssue({code:z.ZodIssueCode.custom,message:'effectiveTo debe ser posterior a effectiveFrom.',path:['effectiveTo']});});
export const createRuleInput=z.object({ scopeType:z.enum(['company','site','collective']),scopeId:z.string().uuid(),name:z.string().trim().min(1).max(160) });
export const createCalendarInput=z.object({name:z.string().trim().min(1).max(160),timeZone:z.string().min(1),workingDays:z.array(z.number().int().min(1).max(7)).min(1).max(7),holidays:z.array(date).max(3660)}).superRefine((v,ctx)=>{try{assertIana(v.timeZone)}catch{ctx.addIssue({code:z.ZodIssueCode.custom,message:'Zona IANA inválida.',path:['timeZone']})};if(new Set(v.workingDays).size!==v.workingDays.length)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Los días laborables no pueden repetirse.',path:['workingDays']});if(new Set(v.holidays).size!==v.holidays.length)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Los festivos no pueden repetirse.',path:['holidays']});});
export const createShiftInput=z.object({name:z.string().trim().min(1).max(160),segments});
export const createVersionInput=versionInput;
export type AuditContext={actorId:string;correlationId:string};
export async function createRule(input:z.infer<typeof createRuleInput>, audit:AuditContext){const r=await db.query<{id:string;createdAt:Date;updatedAt:Date}>(`INSERT INTO work_rules(scope_type,scope_id,name) VALUES($1,$2,$3) RETURNING id,created_at AS "createdAt",updated_at AS "updatedAt"`,[input.scopeType,input.scopeId,input.name]);const rule={...input,...r.rows[0],status:'active'};await appendAudit({actorType:'user',actorId:audit.actorId,action:'work-rule.created',resourceType:'work-rule',resourceId:rule.id,result:'success',correlationId:audit.correlationId,changes:{scopeType:input.scopeType,scopeId:input.scopeId,name:input.name}});return rule;}
export async function listRules(){return (await db.query(`SELECT id,scope_type AS "scopeType",scope_id AS "scopeId",name,status,deactivated_at AS "deactivatedAt",created_at AS "createdAt",updated_at AS "updatedAt" FROM work_rules ORDER BY created_at DESC`)).rows;}
export async function deactivateRule(id:string,audit:AuditContext){const r=await db.query<{id:string}>(`UPDATE work_rules SET status='inactive',deactivated_at=clock_timestamp(),updated_at=clock_timestamp() WHERE id=$1 AND status='active' RETURNING id`,[id]);if(!r.rowCount)return null;await appendAudit({actorType:'user',actorId:audit.actorId,action:'work-rule.deactivated',resourceType:'work-rule',resourceId:id,result:'success',correlationId:audit.correlationId,changes:{}});return {id,status:'inactive' as const};}
export async function createCalendar(input:z.infer<typeof createCalendarInput>,audit:AuditContext){const r=await db.query<{id:string;createdAt:Date;updatedAt:Date}>(`INSERT INTO calendars(name,time_zone,working_days,holidays) VALUES($1,$2,$3,$4) RETURNING id,created_at AS "createdAt",updated_at AS "updatedAt"`,[input.name,input.timeZone,JSON.stringify(input.workingDays),JSON.stringify(input.holidays)]);const value={...input,...r.rows[0]};await appendAudit({actorType:'user',actorId:audit.actorId,action:'calendar.created',resourceType:'calendar',resourceId:value.id,result:'success',correlationId:audit.correlationId,changes:{name:input.name,timeZone:input.timeZone}});return value;}
export async function listCalendars(){return (await db.query(`SELECT id,name,time_zone AS "timeZone",working_days AS "workingDays",holidays,created_at AS "createdAt",updated_at AS "updatedAt" FROM calendars ORDER BY created_at DESC`)).rows;}
export async function createShift(input:z.infer<typeof createShiftInput>,audit:AuditContext){const r=await db.query<{id:string;createdAt:Date;updatedAt:Date}>(`INSERT INTO shifts(name,segments) VALUES($1,$2) RETURNING id,created_at AS "createdAt",updated_at AS "updatedAt"`,[input.name,JSON.stringify(input.segments)]);const value={...input,...r.rows[0]};await appendAudit({actorType:'user',actorId:audit.actorId,action:'shift.created',resourceType:'shift',resourceId:value.id,result:'success',correlationId:audit.correlationId,changes:{name:input.name,segments:input.segments}});return value;}
export async function listShifts(){return (await db.query(`SELECT id,name,segments,created_at AS "createdAt",updated_at AS "updatedAt" FROM shifts ORDER BY created_at DESC`)).rows;}
export async function createVersion(workRuleId:string,input:z.infer<typeof createVersionInput>,audit:AuditContext){assertIana(input.timeZone);const calendar=input.calendarId?await db.query<{id:string;name:string;timeZone:string;workingDays:number[];holidays:string[]}>(`SELECT id,name,time_zone AS "timeZone",working_days AS "workingDays",holidays FROM calendars WHERE id=$1`,[input.calendarId]):null;const shift=input.shiftId?await db.query<{id:string;name:string;segments:any[]}>(`SELECT id,name,segments FROM shifts WHERE id=$1`,[input.shiftId]):null;if((input.calendarId&&!calendar?.rowCount)||(input.shiftId&&!shift?.rowCount))throw new Error('CONFIGURATION_REFERENCE_NOT_FOUND');const r=await db.query<{id:string;createdAt:Date}>(`INSERT INTO rule_versions(work_rule_id,effective_from,effective_to,time_zone,expected_minutes,pause_policy,calendar_id,shift_id,calendar_snapshot,shift_snapshot,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id,created_at AS "createdAt"`,[workRuleId,input.effectiveFrom,input.effectiveTo??null,input.timeZone,input.expectedMinutes,JSON.stringify(input.pausePolicy),input.calendarId??null,input.shiftId??null,calendar?.rows[0]?JSON.stringify(calendar.rows[0]):null,shift?.rows[0]?JSON.stringify(shift.rows[0]):null,audit.actorId]);const value={id:r.rows[0].id,workRuleId,...input,calendar:calendar?.rows[0]??null,shift:shift?.rows[0]??null,createdAt:r.rows[0].createdAt};await appendAudit({actorType:'user',actorId:audit.actorId,action:'rule-version.published',resourceType:'rule-version',resourceId:value.id,result:'success',correlationId:audit.correlationId,changes:{workRuleId,effectiveFrom:input.effectiveFrom,effectiveTo:input.effectiveTo??null,pausePolicy:input.pausePolicy}});return value;}
export async function listVersions(workRuleId?:string){return (await db.query(`SELECT id,work_rule_id AS "workRuleId",effective_from::text AS "effectiveFrom",effective_to::text AS "effectiveTo",time_zone AS "timeZone",expected_minutes AS "expectedMinutes",pause_policy AS "pausePolicy",calendar_snapshot AS calendar,shift_snapshot AS shift,created_at AS "createdAt" FROM rule_versions ${workRuleId?'WHERE work_rule_id=$1':''} ORDER BY effective_from DESC`,workRuleId?[workRuleId]:[])).rows;}
