import { createHash } from 'node:crypto';
import type pg from 'pg';
import { appendAudit } from '@/audit/audit-writer';
import { db } from '@/shared/db';
import { config } from '@/shared/config';
import type { ScopedActor } from '@/permissions/authorizer';
import { assertAuthorized, assertSiteScope } from '@/permissions/authorizer';
import type { CorrectionRequest, ProposedEffect } from './contracts';

type Row={id:string;employeeId:string;siteId:string;laborDate:string;kind:'time_event'|'calculation_incident';timeEventId:string|null;dailyCalculationVersionId:string|null;proposedEffect:ProposedEffect;reason:string;status:'pending'|'approved'|'rejected';requestedByUserId:string;requestedAt:Date;decisionId:string|null;decision:string|null;decisionReason:string|null;decidedByUserId:string|null;decidedAt:Date|null;effectId:string|null};
const columns=`r.id,r.employee_id AS "employeeId",r.site_id AS "siteId",r.labor_date::text AS "laborDate",r.kind,r.time_event_id AS "timeEventId",r.daily_calculation_version_id AS "dailyCalculationVersionId",r.proposed_effect AS "proposedEffect",r.reason,r.status,r.requested_by_user_id AS "requestedByUserId",r.requested_at AS "requestedAt",d.id AS "decisionId",d.decision,d.reason AS "decisionReason",d.decided_by_user_id AS "decidedByUserId",d.decided_at AS "decidedAt",e.id AS "effectId"`;
const map=(r:Row):CorrectionRequest=>({id:r.id,employeeId:r.employeeId,siteId:r.siteId,laborDate:r.laborDate,kind:r.kind,timeEventId:r.timeEventId,dailyCalculationVersionId:r.dailyCalculationVersionId,proposedEffect:r.proposedEffect,reason:r.reason,status:r.status,requestedByUserId:r.requestedByUserId,requestedAt:r.requestedAt.toISOString(),decision:r.decisionId?{id:r.decisionId,decision:r.decision as 'approved'|'rejected',reason:r.decisionReason,decidedByUserId:r.decidedByUserId!,decidedAt:r.decidedAt!.toISOString()}:null,effectId:r.effectId});
const fingerprint=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
async function row(client:pg.Pool|pg.PoolClient,id:string){const q=await client.query<Row>(`SELECT ${columns} FROM correction_requests r LEFT JOIN correction_decisions d ON d.correction_request_id=r.id LEFT JOIN correction_effects e ON e.correction_request_id=r.id WHERE r.id=$1`,[id]);return q.rows[0]??null;}

export async function createCorrection(actor:ScopedActor, employeeId:string, input:{kind:'time_event'|'calculation_incident';timeEventId?:string;dailyCalculationVersionId?:string;proposedEffect:ProposedEffect;reason:string}, correlationId:string){
  assertAuthorized(actor,'correction.create:self'); if(actor.id!==await userForEmployee(employeeId)) throw new Error('CORRECTION_NOT_OWN');
  const client=await db.connect(); try{await client.query('BEGIN'); let source:{siteId:string;laborDate:string;ruleVersionId:string;timeZone:string}|null=null;
    if(input.kind==='time_event') source=(await client.query<any>(`SELECT t.site_id AS "siteId",t.labor_date::text AS "laborDate",t.rule_version_id AS "ruleVersionId",t.effective_time_zone AS "timeZone" FROM time_events t JOIN employees e ON e.id=t.employee_id JOIN companies c ON c.id=e.company_id WHERE t.id=$1 AND t.employee_id=$2 AND c.environment_id=$3`,[input.timeEventId,employeeId,config.ENVIRONMENT_ID])).rows[0]??null;
    else source=(await client.query<any>(`SELECT d.site_id AS "siteId",d.labor_date::text AS "laborDate",d.rule_version_id AS "ruleVersionId",d.effective_time_zone AS "timeZone" FROM daily_calculation_versions v JOIN daily_calculations d ON d.id=v.daily_calculation_id JOIN employees e ON e.id=d.employee_id JOIN companies c ON c.id=e.company_id WHERE v.id=$1 AND d.employee_id=$2 AND c.environment_id=$3`,[input.dailyCalculationVersionId,employeeId,config.ENVIRONMENT_ID])).rows[0]??null;
    if(!source)throw new Error('CORRECTION_SOURCE_NOT_FOUND');
    const created=(await client.query<Row>(`INSERT INTO correction_requests(employee_id,site_id,labor_date,kind,time_event_id,daily_calculation_version_id,proposed_effect,reason,requested_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,employee_id AS "employeeId",site_id AS "siteId",labor_date::text AS "laborDate",kind,time_event_id AS "timeEventId",daily_calculation_version_id AS "dailyCalculationVersionId",proposed_effect AS "proposedEffect",reason,status,requested_by_user_id AS "requestedByUserId",requested_at AS "requestedAt",NULL::uuid AS "decisionId",NULL::text AS decision,NULL::text AS "decisionReason",NULL::uuid AS "decidedByUserId",NULL::timestamptz AS "decidedAt",NULL::uuid AS "effectId"`,[employeeId,source.siteId,source.laborDate,input.kind,input.timeEventId??null,input.dailyCalculationVersionId??null,JSON.stringify(input.proposedEffect),input.reason,actor.id])).rows[0];
    await appendAudit({actorType:'user',actorId:actor.id,action:'correction.requested',resourceType:'correction-request',resourceId:created.id,result:'success',correlationId,changes:{employeeId,siteId:source.siteId,laborDate:source.laborDate,kind:input.kind,timeEventId:input.timeEventId??null,dailyCalculationVersionId:input.dailyCalculationVersionId??null}}); await client.query('COMMIT'); return map(created);
  }catch(e){await client.query('ROLLBACK').catch(()=>undefined);throw e;}finally{client.release();}
}
export async function userForEmployee(employeeId:string){const q=await db.query<{userId:string}>(`SELECT e.user_id AS "userId" FROM employees e JOIN companies c ON c.id=e.company_id WHERE e.id=$1 AND e.is_active AND c.environment_id=$2`,[employeeId,config.ENVIRONMENT_ID]);return q.rows[0]?.userId??null;}
export async function listCorrections(actor:ScopedActor, employeeId?:string){if(employeeId){const own=actor.id===await userForEmployee(employeeId);if(own)assertAuthorized(actor,'correction.read:self');else assertAuthorized(actor,'correction.read:scope');}else assertAuthorized(actor,'correction.read:scope');const q=await db.query<Row>(`SELECT ${columns} FROM correction_requests r LEFT JOIN correction_decisions d ON d.correction_request_id=r.id LEFT JOIN correction_effects e ON e.correction_request_id=r.id ${employeeId?'WHERE r.employee_id=$1':''} ORDER BY r.requested_at DESC`,employeeId?[employeeId]:[]);const values=q.rows.map(map);for(const value of values){if(actor.id!==await userForEmployee(value.employeeId))assertSiteScope(actor,value.siteId);}return values;}
export async function decideCorrection(actor:ScopedActor,id:string,input:{decision:'approved'|'rejected';reason?:string},key:string,correlationId:string){assertAuthorized(actor,'correction.decide');const client=await db.connect();try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1, 606))',[id]);const current=await row(client,id);if(!current)throw new Error('CORRECTION_NOT_FOUND');assertSiteScope(actor,current.siteId);const requestFingerprint=fingerprint(input);if(current.status!=='pending'){if(current.decision&&current.decision===input.decision&&fingerprint({decision:current.decision,reason:current.decisionReason??undefined})===requestFingerprint){await client.query('COMMIT');return {correction:map(current),replayed:true};}throw new Error('CORRECTION_ALREADY_DECIDED');}
  const decision=(await client.query<{id:string}>(`INSERT INTO correction_decisions(correction_request_id,decision,reason,request_fingerprint,decided_by_user_id) VALUES($1,$2,$3,$4,$5) RETURNING id`,[id,input.decision,input.reason??null,requestFingerprint,actor.id])).rows[0];let effectId:string|null=null;
  if(input.decision==='approved'){const source=(await client.query<any>(`SELECT COALESCE(t.rule_version_id,d.rule_version_id) AS "ruleVersionId",COALESCE(t.effective_time_zone,d.effective_time_zone) AS "timeZone" FROM correction_requests r LEFT JOIN time_events t ON t.id=r.time_event_id LEFT JOIN daily_calculation_versions v ON v.id=r.daily_calculation_version_id LEFT JOIN daily_calculations d ON d.id=v.daily_calculation_id WHERE r.id=$1`,[id])).rows[0];const effect=(await client.query<{id:string}>(`INSERT INTO correction_effects(correction_request_id,employee_id,site_id,labor_date,replaces_time_event_id,event_type,occurred_at,rule_version_id,effective_time_zone,approved_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id`,[id,current.employeeId,current.siteId,current.laborDate,current.timeEventId,current.proposedEffect.eventType,current.proposedEffect.occurredAt,source.ruleVersionId,source.timeZone,actor.id])).rows[0];effectId=effect.id;await client.query('INSERT INTO domain_event_outbox(name,payload,correlation_id) VALUES($1,$2,$3),($4,$5,$3)',['correction.decided',JSON.stringify({correctionId:id,decision:'approved',effectId,employeeId:current.employeeId,laborDate:current.laborDate}),correlationId,'time-calculation.recalculation-requested',JSON.stringify({employeeId:current.employeeId,laborDate:current.laborDate,correctionId:id})]);}
  await client.query('UPDATE correction_requests SET status=$2,decision_id=$3 WHERE id=$1',[id,input.decision,decision.id]);await appendAudit({actorType:'user',actorId:actor.id,action:`correction.${input.decision}`,resourceType:'correction-request',resourceId:id,result:'success',correlationId,changes:{employeeId:current.employeeId,siteId:current.siteId,laborDate:current.laborDate,reasonRequired:input.decision==='rejected',effectId}});if(effectId)await appendAudit({actorType:'user',actorId:actor.id,action:'correction.effect.applied',resourceType:'correction-effect',resourceId:effectId,result:'success',correlationId,changes:{correctionId:id,employeeId:current.employeeId,laborDate:current.laborDate}});const updated=await row(client,id);await client.query('COMMIT');return {correction:map(updated!),replayed:false};
}catch(e){await client.query('ROLLBACK').catch(()=>undefined);throw e;}finally{client.release();}}
