import { db } from '@/shared/db';
import { config } from '@/shared/config';
import { appendAudit } from '@/audit/audit-writer';
import type { ScopedActor } from '@/permissions/authorizer';

type Audit = { actor: ScopedActor; correlationId?: string; cid?: string };
const companyColumns = 'id,name,legal_identifier AS "legalIdentifier",is_active AS "isActive",deactivated_at AS "deactivatedAt",created_at AS "createdAt",updated_at AS "updatedAt"';
const siteColumns = 'id,company_id AS "companyId",name,time_zone AS "timeZone",is_active AS "isActive",deactivated_at AS "deactivatedAt",created_at AS "createdAt",updated_at AS "updatedAt"';
const employeeColumns = 'e.id,e.company_id AS "companyId",e.user_id AS "userId",e.display_name AS "displayName",e.is_active AS "isActive",e.deactivated_at AS "deactivatedAt",e.created_at AS "createdAt",e.updated_at AS "updatedAt"';
const employeeReturnColumns = 'id,company_id AS "companyId",user_id AS "userId",display_name AS "displayName",is_active AS "isActive",deactivated_at AS "deactivatedAt",created_at AS "createdAt",updated_at AS "updatedAt"';
const employmentColumns = 'id,employee_id AS "employeeId",site_id AS "siteId",manager_employee_id AS "managerEmployeeId",effective_from AS "effectiveFrom",effective_to AS "effectiveTo",ended_at AS "endedAt",created_at AS "createdAt",updated_at AS "updatedAt"';
async function audit(a: Audit, action:string, resourceType:string, resourceId:string, changes:Record<string, unknown>) { await appendAudit({actorType:'user',actorId:a.actor.id,action,resourceType,resourceId,result:'success',correlationId:a.correlationId ?? a.cid!,changes}); }
export async function company() { return (await db.query(`SELECT ${companyColumns} FROM companies WHERE environment_id=$1`,[config.ENVIRONMENT_ID])).rows[0] ?? null; }
export async function createCompany(input:{name:string;legalIdentifier?:string|null}, a:Audit) { const r=await db.query(`INSERT INTO companies(environment_id,name,legal_identifier) VALUES($1,$2,$3) ON CONFLICT(environment_id) DO NOTHING RETURNING ${companyColumns}`,[config.ENVIRONMENT_ID,input.name,input.legalIdentifier ?? null]); if(!r.rowCount) return null; await audit(a,'company.created','company',r.rows[0].id,{name:input.name}); return r.rows[0]; }
export async function updateCompany(input:{name:string;legalIdentifier?:string|null}, a:Audit) { const r=await db.query(`UPDATE companies SET name=$2,legal_identifier=$3,updated_at=clock_timestamp() WHERE environment_id=$1 AND is_active=true RETURNING ${companyColumns}`,[config.ENVIRONMENT_ID,input.name,input.legalIdentifier ?? null]); if(!r.rowCount)return null; await audit(a,'company.updated','company',r.rows[0].id,{name:input.name}); return r.rows[0]; }
export async function deactivateCompany(a:Audit) { const r=await db.query(`UPDATE companies SET is_active=false,deactivated_at=clock_timestamp(),updated_at=clock_timestamp() WHERE environment_id=$1 AND is_active=true RETURNING ${companyColumns}`,[config.ENVIRONMENT_ID]); if(!r.rowCount)return null; await audit(a,'company.deactivated','company',r.rows[0].id,{}); return r.rows[0]; }
export async function listSites(includeInactive=false, siteIds?:string[]) { const scoped=siteIds === undefined ? '' : siteIds.length ? 'AND s.id = ANY($2::uuid[])' : 'AND false'; return (await db.query(`SELECT ${siteColumns} FROM sites s JOIN companies c ON c.id=s.company_id WHERE c.environment_id=$1 ${includeInactive?'':'AND s.is_active=true'} ${scoped} ORDER BY s.name`,siteIds?.length?[config.ENVIRONMENT_ID,siteIds]:[config.ENVIRONMENT_ID])).rows; }
export async function getSite(id:string) { return (await db.query(`SELECT ${siteColumns} FROM sites s JOIN companies c ON c.id=s.company_id WHERE s.id=$1 AND c.environment_id=$2`,[id,config.ENVIRONMENT_ID])).rows[0] ?? null; }
export async function createSite(input:{name:string;timeZone:string},a:Audit) { const r=await db.query(`INSERT INTO sites(company_id,name,time_zone) SELECT id,$2,$3 FROM companies WHERE environment_id=$1 AND is_active=true RETURNING ${siteColumns}`,[config.ENVIRONMENT_ID,input.name,input.timeZone]); if(!r.rowCount)return null; await audit(a,'site.created','site',r.rows[0].id,{name:input.name,timeZone:input.timeZone});return r.rows[0]; }
export async function updateSite(id:string,input:{name:string;timeZone:string},a:Audit) { const r=await db.query(`UPDATE sites s SET name=$3,time_zone=$4,updated_at=clock_timestamp() FROM companies c WHERE s.id=$1 AND s.company_id=c.id AND c.environment_id=$2 AND s.is_active=true RETURNING ${siteColumns}`,[id,config.ENVIRONMENT_ID,input.name,input.timeZone]);if(!r.rowCount)return null;await audit(a,'site.updated','site',id,{name:input.name,timeZone:input.timeZone});return r.rows[0]; }
export async function deactivateSite(id:string,a:Audit) { const r=await db.query(`UPDATE sites s SET is_active=false,deactivated_at=clock_timestamp(),updated_at=clock_timestamp() FROM companies c WHERE s.id=$1 AND s.company_id=c.id AND c.environment_id=$2 AND s.is_active=true RETURNING ${siteColumns}`,[id,config.ENVIRONMENT_ID]);if(!r.rowCount)return null;await audit(a,'site.deactivated','site',id,{});return r.rows[0]; }
export async function listEmployees(includeInactive=false, siteIds?:string[]) { const scoped=siteIds === undefined ? '' : siteIds.length ? 'AND EXISTS(SELECT 1 FROM employments em WHERE em.employee_id=e.id AND em.site_id = ANY($2::uuid[]))' : 'AND false'; return (await db.query(`SELECT ${employeeColumns} FROM employees e JOIN companies c ON c.id=e.company_id WHERE c.environment_id=$1 ${includeInactive?'':'AND e.is_active=true'} ${scoped} ORDER BY e.display_name`,siteIds?.length?[config.ENVIRONMENT_ID,siteIds]:[config.ENVIRONMENT_ID])).rows; }
export async function getEmployee(id:string) {return (await db.query(`SELECT ${employeeColumns} FROM employees e JOIN companies c ON c.id=e.company_id WHERE e.id=$1 AND c.environment_id=$2`,[id,config.ENVIRONMENT_ID])).rows[0]??null;}
export async function employeeForUser(userId:string) {return (await db.query(`SELECT ${employeeColumns} FROM employees e JOIN companies c ON c.id=e.company_id WHERE e.user_id=$1 AND c.environment_id=$2 AND e.is_active=true`,[userId,config.ENVIRONMENT_ID])).rows[0]??null;}
export async function createEmployee(input:{displayName:string;userId?:string|null},a:Audit) {const r=await db.query(`INSERT INTO employees(company_id,display_name,user_id) SELECT id,$2,$3 FROM companies WHERE environment_id=$1 AND is_active=true RETURNING ${employeeReturnColumns}`,[config.ENVIRONMENT_ID,input.displayName,input.userId??null]);if(!r.rowCount)return null;await audit(a,'employee.created','employee',r.rows[0].id,{displayName:input.displayName,userLinked:!!input.userId});return r.rows[0];}
export async function updateEmployee(id:string,input:{displayName:string;userId?:string|null},a:Audit) {const r=await db.query(`UPDATE employees e SET display_name=$3,user_id=$4,updated_at=clock_timestamp() FROM companies c WHERE e.id=$1 AND e.company_id=c.id AND c.environment_id=$2 AND e.is_active=true RETURNING ${employeeColumns}`,[id,config.ENVIRONMENT_ID,input.displayName,input.userId??null]);if(!r.rowCount)return null;await audit(a,'employee.updated','employee',id,{displayName:input.displayName,userLinked:!!input.userId});return r.rows[0];}
export async function deactivateEmployee(id:string,a:Audit) {const r=await db.query(`UPDATE employees e SET is_active=false,deactivated_at=clock_timestamp(),updated_at=clock_timestamp() FROM companies c WHERE e.id=$1 AND e.company_id=c.id AND c.environment_id=$2 AND e.is_active=true RETURNING ${employeeColumns}`,[id,config.ENVIRONMENT_ID]);if(!r.rowCount)return null;await audit(a,'employee.deactivated','employee',id,{});return r.rows[0];}
export async function listEmployments(employeeId?:string, siteIds?:string[]) {const params:unknown[]=[config.ENVIRONMENT_ID];let where='';if(employeeId){params.push(employeeId);where+=' AND em.employee_id=$2';}if(siteIds !== undefined){if(!siteIds.length)where+=' AND false';else {params.push(siteIds);where+=` AND em.site_id = ANY($${params.length}::uuid[])`;}}const r=await db.query(`SELECT ${employmentColumns} FROM employments em JOIN employees e ON e.id=em.employee_id JOIN companies c ON c.id=e.company_id WHERE c.environment_id=$1${where} ORDER BY em.effective_from DESC`,params);return r.rows;}
export async function getEmployment(id:string) {return (await db.query(`SELECT ${employmentColumns} FROM employments em JOIN employees e ON e.id=em.employee_id JOIN companies c ON c.id=e.company_id WHERE em.id=$1 AND c.environment_id=$2`,[id,config.ENVIRONMENT_ID])).rows[0]??null;}
export async function createEmployment(input:{employeeId:string;siteId:string;managerEmployeeId?:string|null;effectiveFrom:string;effectiveTo?:string|null},a:Audit) { const valid=await validEmploymentReferences(input);if(!valid)return null;const r=await db.query(`INSERT INTO employments(employee_id,site_id,manager_employee_id,effective_from,effective_to) VALUES($1,$2,$3,$4,$5) RETURNING ${employmentColumns}`,[input.employeeId,input.siteId,input.managerEmployeeId??null,input.effectiveFrom,input.effectiveTo??null]);await audit(a,'employment.created','employment',r.rows[0].id,{employeeId:input.employeeId,siteId:input.siteId,managerEmployeeId:input.managerEmployeeId??null});return r.rows[0]; }
export async function updateEmployment(id:string,input:{employeeId:string;siteId:string;managerEmployeeId?:string|null;effectiveFrom:string;effectiveTo?:string|null},a:Audit) {if(!await validEmploymentReferences(input))return null;const r=await db.query(`UPDATE employments em SET employee_id=$2,site_id=$3,manager_employee_id=$4,effective_from=$5,effective_to=$6,ended_at=CASE WHEN $6 IS NULL THEN NULL ELSE clock_timestamp() END,updated_at=clock_timestamp() FROM employees existing JOIN companies c ON c.id=existing.company_id WHERE em.id=$1 AND em.employee_id=existing.id AND c.environment_id=$7 RETURNING ${employmentColumns}`,[id,input.employeeId,input.siteId,input.managerEmployeeId??null,input.effectiveFrom,input.effectiveTo??null,config.ENVIRONMENT_ID]);if(!r.rowCount)return null;await audit(a,'employment.updated','employment',id,{siteId:input.siteId,managerEmployeeId:input.managerEmployeeId??null});return r.rows[0];}
export async function endEmployment(id:string,a:Audit) {const r=await db.query(`UPDATE employments em SET effective_to=GREATEST(em.effective_from + 1, current_date),ended_at=clock_timestamp(),updated_at=clock_timestamp() FROM employees e JOIN companies c ON c.id=e.company_id WHERE em.id=$1 AND em.employee_id=e.id AND c.environment_id=$2 AND em.effective_to IS NULL RETURNING ${employmentColumns}`,[id,config.ENVIRONMENT_ID]);if(!r.rowCount)return null;await audit(a,'employment.ended','employment',id,{});return r.rows[0];}
async function validEmploymentReferences(input:{employeeId:string;siteId:string;managerEmployeeId?:string|null;effectiveFrom:string}) {const r=await db.query<{valid:boolean}>(`SELECT EXISTS(SELECT 1 FROM employees e JOIN companies c ON c.id=e.company_id JOIN sites s ON s.company_id=c.id WHERE e.id=$1 AND s.id=$2 AND c.environment_id=$3 AND e.is_active AND s.is_active) AND ($4::uuid IS NULL OR EXISTS(SELECT 1 FROM employees m JOIN employments me ON me.employee_id=m.id WHERE m.id=$4 AND m.is_active AND me.site_id=$2 AND me.effective_from <= $5::date AND (me.effective_to IS NULL OR me.effective_to > $5::date))) AS valid`,[input.employeeId,input.siteId,config.ENVIRONMENT_ID,input.managerEmployeeId??null,input.effectiveFrom]);return r.rows[0].valid;}
