'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import type { TimeEvent, TimeEventType } from '@/time-events/contracts';
import type { PersistedDailyCalculation } from '@/time-calculation/contracts';
import type { CorrectionRequest } from '@/corrections/contracts';
import type { WorkdayStatus } from '@/workday-status/contracts';
import { LogoutButton } from '@/auth/ui';
import { LoadingBlock, StatusBadge, StatusNotice } from '@/ui/feedback';
import { employeeApi } from './api';
import { actionLabels, availableActions, dateTime, dayStatus, errorMessage, eventLabels, minutes } from './presentation';

const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Europe/Madrid' }).format(new Date());
const correctionKind = (status: CorrectionRequest['status']) => status === 'approved' ? 'success' : status === 'rejected' ? 'error' : 'warning';
const correctionLabel = (status: CorrectionRequest['status']) => status === 'approved' ? 'Aprobada' : status === 'rejected' ? 'Rechazada' : 'Pendiente de revisión';

export function EmployeeNav() {
  return <nav className="employee-nav" aria-label="Navegación de empleado"><Link href="/employee">Hoy</Link><Link href="/employee/history">Historial</Link><Link href="/employee/corrections">Correcciones</Link><LogoutButton /></nav>;
}

export function Events({ events, linkCorrections = false }: { events: TimeEvent[]; linkCorrections?: boolean }) {
  return <ol className="employee-list">{events.map((event) => <li key={event.id}><span><strong>{eventLabels[event.eventType]}</strong><small>{event.method === 'web' ? 'Registrado desde la web' : 'Registrado en kiosco'}</small></span><span><time dateTime={event.occurredAt}>{dateTime(event.occurredAt, event.effectiveTimeZone)}</time>{linkCorrections && <Link href={`/employee/corrections?kind=time_event&reference=${event.id}`}>Solicitar corrección</Link>}</span></li>)}</ol>;
}

export function Calculation({ calculation }: { calculation: PersistedDailyCalculation }) {
  return <section className="employee-section" aria-labelledby="calculation-title"><h2 id="calculation-title">Resumen de jornada</h2><dl className="employee-metrics"><div><dt>Tiempo efectivo</dt><dd>{minutes(calculation.effectiveMinutes)}</dd></div><div><dt>Pausas registradas</dt><dd>{minutes(calculation.registeredBreakMinutes)}</dd></div><div><dt>Jornada esperada</dt><dd>{minutes(calculation.expectedMinutes)}</dd></div><div><dt>Diferencia registrada</dt><dd>{minutes(calculation.differenceMinutes)}</dd></div></dl><p className="informative">La diferencia y los excesos son informativos. No son nómina, sanción ni un derecho económico definitivo.</p><details className="technical-details"><summary>Información técnica de esta jornada</summary><p>Regla aplicada: <code>{calculation.ruleVersionId}</code> · algoritmo <code>{calculation.algorithmVersion}</code> · zona horaria {calculation.effectiveTimeZone}.</p></details>{calculation.incidents.length > 0 && <section><h3>Incidencias que requieren revisión</h3><ul>{calculation.incidents.map((incident, index) => <li key={`${incident.code}-${index}`}>{incident.message}</li>)}</ul><Link href={`/employee/corrections?kind=calculation_incident&reference=${calculation.id}`}>Solicitar corrección de una incidencia</Link></section>}</section>;
}

const workdayLabels:Record<WorkdayStatus['status'],string>={not_started:'Sin iniciar',working:'En curso',on_break:'En pausa',ended:'Finalizada'};
function WorkdayState({value,loading}:{value:WorkdayStatus|null;loading:boolean}){return <section className="employee-section" aria-labelledby="workday-status-title" aria-busy={loading}><h2 id="workday-status-title">Estado de jornada</h2>{loading?<LoadingBlock>Actualizando estado de jornada…</LoadingBlock>:!value?<StatusNotice kind="info">No se pudo cargar la proyección de jornada. Puedes seguir fichando y reintentar la consulta.</StatusNotice>:<><p><StatusBadge kind={value.status==='working'?'success':value.status==='on_break'?'warning':'info'}>{workdayLabels[value.status]}</StatusBadge></p><dl className="employee-metrics"><div><dt>Tiempo efectivo acumulado</dt><dd>{value.effectiveMinutes===null?'Sin registros':minutes(value.effectiveMinutes)}</dd></div><div><dt>Última confirmación</dt><dd>{value.lastConfirmedAt?dateTime(value.lastConfirmedAt,value.effectiveTimeZone):'Todavía no hay fichajes'}</dd></div></dl><p className="informative">Este tiempo es informativo y de registro. No es nómina, sanción, productividad ni una decisión disciplinaria.</p><p className="subtle">Las pausas son manuales y visibles. Si no puedes actualizar el estado, revisa tu conexión y vuelve a intentarlo.</p></>}</section>}

export function Dashboard() {
  const [events, setEvents] = useState<TimeEvent[]>([]); const [calculation, setCalculation] = useState<PersistedDailyCalculation | null>(); const [status,setStatus]=useState<WorkdayStatus|null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<TimeEventType>(); const [notice, setNotice] = useState<string>(); const [failure, setFailure] = useState<string>();
  const load = async () => { setLoading(true); setFailure(undefined); try { const [employee, items,projection] = await Promise.all([employeeApi.me(), employeeApi.events(),employeeApi.status()]); setEvents(items);setStatus(projection); try { setCalculation(await employeeApi.calculation(employee.id, projection.laborDate||today())); } catch { setCalculation(null); } } catch (error) { setFailure(errorMessage(error)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  useEffect(()=>{const onFocus=()=>void load();window.addEventListener('focus',onFocus);const timer=status?.status==='working'?window.setInterval(()=>void load(),60000):undefined;return()=>{window.removeEventListener('focus',onFocus);if(timer)window.clearInterval(timer);};},[status?.status]);
  const clock = async (type: TimeEventType) => { setBusy(type); setNotice(undefined); setFailure(undefined); try { const result = await employeeApi.clock(type); setNotice(`${actionLabels[type]} ${result.replayed ? 'ya estaba confirmada' : 'confirmada'} a las ${dateTime(result.event.recordedAt, result.event.effectiveTimeZone)}.`); await load(); } catch (error) { setFailure(errorMessage(error)); } finally { setBusy(undefined); } };
  const last = events[0]; const actions = availableActions(last);
  return <main className="employee-shell"><EmployeeNav /><header><p className="eyebrow">MI JORNADA</p><h1>{loading ? 'Cargando jornada…' : `Jornada ${status?workdayLabels[status.status]:dayStatus(last, calculation)}`}</h1><p className="subtle">Consulta tu estado actual y registra sólo la acción que corresponde.</p></header>{failure && <StatusNotice kind="error">{failure} <button className="link-button" onClick={() => void load()}>Reintentar la consulta</button> <Link href="/admin">Si eres responsable o administración, abre Administración</Link>.</StatusNotice>}{notice && <StatusNotice kind="success">{notice}</StatusNotice>}<WorkdayState value={status} loading={loading}/>{!failure && <><section className="employee-section" aria-labelledby="next-action-title" aria-busy={!!busy}>{loading ? <LoadingBlock>Consultando tus registros…</LoadingBlock> : <><h2 id="next-action-title">Siguiente acción</h2><p className="subtle">El botón se bloquea hasta recibir la confirmación.</p><div className="clock-actions">{actions.map((action) => <button key={action} onClick={() => void clock(action)} disabled={!!busy}>{busy === action ? 'Registrando…' : actionLabels[action]}</button>)}</div></>}</section>{calculation && <Calculation calculation={calculation} />}<section className="employee-section"><h2>Últimos registros</h2>{events.length ? <Events events={events.slice(0, 5)} /> : <p className="subtle">Aún no has registrado ningún fichaje. La primera acción disponible será tu entrada.</p>}<Link href="/employee/history">Ver historial completo</Link></section></>}</main>;
}

export function History() {
  const [events, setEvents] = useState<TimeEvent[]>([]); const [failure, setFailure] = useState<string>(); useEffect(() => { employeeApi.events().then(setEvents).catch((error) => setFailure(errorMessage(error))); }, []); const dates = [...new Set(events.map((event) => event.laborDate))];
  return <main className="employee-shell"><EmployeeNav /><h1>Mi historial</h1><p className="subtle">Consulta tus registros por día. Cada fichaje original se conserva aunque solicites una corrección.</p>{failure ? <StatusNotice kind="error">{failure}</StatusNotice> : !events.length ? <p className="subtle">No hay registros todavía.</p> : <ul className="day-list">{dates.map((date) => { const records = events.filter((event) => event.laborDate === date); return <li key={date}><Link href={`/employee/history/${date}`}><strong>{date}</strong><span>{records.length} {records.length === 1 ? 'registro' : 'registros'} · Ver detalle</span></Link></li>; })}</ul>}</main>;
}

export function DayDetail({ laborDate }: { laborDate: string }) {
  const [events, setEvents] = useState<TimeEvent[]>([]); const [calculation, setCalculation] = useState<PersistedDailyCalculation | null>(); const [failure, setFailure] = useState<string>(); useEffect(() => { Promise.all([employeeApi.me(), employeeApi.events()]).then(async ([employee, items]) => { setEvents(items.filter((event) => event.laborDate === laborDate)); try { setCalculation(await employeeApi.calculation(employee.id, laborDate)); } catch { setCalculation(null); } }).catch((error) => setFailure(errorMessage(error))); }, [laborDate]);
  return <main className="employee-shell"><EmployeeNav /><Link href="/employee/history">← Volver al historial</Link><h1>Jornada del {laborDate}</h1>{failure ? <StatusNotice kind="error">{failure}</StatusNotice> : <><section className="employee-section"><h2>Eventos y pausas</h2>{events.length ? <Events events={events} linkCorrections /> : <p className="subtle">No hay eventos registrados este día.</p>}</section>{calculation ? <Calculation calculation={calculation} /> : <StatusNotice kind="info">El cálculo aún no está disponible para esta jornada.</StatusNotice>}</>}</main>;
}

export function Corrections() {
  const params = useSearchParams(); const requestedKind = params.get('kind') === 'calculation_incident' ? 'calculation_incident' : 'time_event'; const requestedReference = params.get('reference') ?? ''; const [events, setEvents] = useState<TimeEvent[]>([]); const [items, setItems] = useState<CorrectionRequest[]>([]); const [reason, setReason] = useState(''); const [reference, setReference] = useState(requestedReference); const [type, setType] = useState<TimeEventType>('clock_in'); const [occurredAt, setOccurredAt] = useState(''); const [notice, setNotice] = useState<string>(); const [failure, setFailure] = useState<string>(); const [sending, setSending] = useState(false);
  const load = () => Promise.all([employeeApi.events(), employeeApi.corrections()]).then(([eventItems, correctionItems]) => { setEvents(eventItems); setItems(correctionItems); }).catch((error) => setFailure(errorMessage(error))); useEffect(() => { void load(); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setFailure(undefined); if (!reference || !occurredAt || reason.trim().length < 3) { setFailure('Selecciona el registro, la propuesta y un motivo de al menos tres caracteres.'); return; } setSending(true); try { await employeeApi.correction({ kind: requestedKind, ...(requestedKind === 'time_event' ? { timeEventId: reference } : { dailyCalculationVersionId: reference }), proposedEffect: { eventType: type, occurredAt: new Date(occurredAt).toISOString() }, reason }); setReason(''); setOccurredAt(''); setNotice('Solicitud enviada. El registro original no se ha modificado; queda pendiente de decisión humana.'); await load(); } catch (error) { setFailure(errorMessage(error)); } finally { setSending(false); } };
  return <main className="employee-shell"><EmployeeNav /><h1>Solicitar corrección</h1><p className="subtle">Una solicitud añade una propuesta: no edita ni borra el fichaje original. Un responsable autorizado la aprobará o rechazará.</p>{failure && <StatusNotice kind="error">{failure}</StatusNotice>}{notice && <StatusNotice kind="success">{notice}</StatusNotice>}<form className="employee-form" onSubmit={submit} aria-busy={sending}>{requestedKind === 'calculation_incident' ? <StatusNotice kind="info">Solicitud vinculada a la incidencia de la jornada seleccionada.</StatusNotice> : <label>Registro a corregir<select value={reference} onChange={(event) => setReference(event.target.value)} required aria-describedby="record-help"><option value="">Selecciona un registro</option>{events.map((item) => <option key={item.id} value={item.id}>{eventLabels[item.eventType]} · {dateTime(item.occurredAt, item.effectiveTimeZone)}</option>)}</select><span id="record-help" className="field-help">El fichaje original se conservará como evidencia.</span></label>}<label>Acción propuesta<select value={type} onChange={(event) => setType(event.target.value as TimeEventType)}>{Object.entries(eventLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Fecha y hora propuesta<input type="datetime-local" value={occurredAt} onChange={(event) => setOccurredAt(event.target.value)} required /></label><label>Motivo<textarea value={reason} onChange={(event) => setReason(event.target.value)} minLength={3} maxLength={1000} required aria-describedby="reason-help" /><span id="reason-help" className="field-help">Explica brevemente qué ocurrió. Mínimo 3 caracteres.</span></label><button disabled={sending}>{sending ? 'Enviando solicitud…' : 'Enviar solicitud'}</button></form><section className="employee-section"><h2>Seguimiento de solicitudes</h2>{!items.length ? <p className="subtle">No has solicitado correcciones.</p> : <ul className="employee-list">{items.map((item) => <li key={item.id}><span><StatusBadge kind={correctionKind(item.status)}>{correctionLabel(item.status)}</StatusBadge><small>{item.reason}</small></span><span>{item.decision?.reason && <small>Motivo del rechazo: {item.decision.reason}</small>}</span></li>)}</ul>}</section></main>;
}
