import { createHash } from 'node:crypto';
import { appendAudit } from '@/audit/audit-writer';
import { db } from '@/shared/db';
import { assertAuthorized,type ScopedActor } from '@/permissions/authorizer';
import { employeeForUser } from '@/time-events/service';
import { PostgresEmploymentScopeProvider } from '@/company-people/rule-scopes';
import { localDateAt } from '@/work-rules/validation';
import { productModuleStatus } from '@/modules/service';
import { monthPattern,monthStart,priorMonths,summarize,type MonthlyReview, type MonthlyReviewDay } from './contracts';

type CalculationRow={laborDate:string;versionId:string;revision:number;expectedMinutes:number;effectiveMinutes:number;differenceMinutes:number;incidents:unknown[];};
type ExceptionRow={date:string;holiday:string|null;leave:string|null};
type PendingRow={laborDate:string;count:number};
const hash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');

async function context(actor:ScopedActor){assertAuthorized(actor,'time-calculation.read:self');const employeeId=await employeeForUser(actor.id);if(!employeeId)throw new Error('MONTHLY_REVIEW_NOT_FOUND');const now=(await db.query<{now:Date}>('SELECT clock_timestamp() AS now')).rows[0].now.toISOString();const employment=await new PostgresEmploymentScopeProvider().contextForEmployee(employeeId,now);if(!employment)throw new Error('MONTHLY_REVIEW_NOT_FOUND');return {employeeId,now,timeZone:employment.effectiveTimeZone,currentPeriod:localDateAt(now,employment.effectiveTimeZone).slice(0,7)};}
async function assertAvailable(){if(await productModuleStatus('informative_hour_balance')!=='active')throw new Error('MONTHLY_REVIEW_MODULE_INACTIVE');}
function assertPeriod(period:string,currentPeriod:string){if(!monthPattern.test(period)||!priorMonths(currentPeriod).includes(period))throw new Error('MONTHLY_REVIEW_PERIOD_INVALID');}
async function data(employeeId:string,period:string){const start=monthStart(period);const end=`${new Date(`${start}T12:00:00.000Z`).getUTCFullYear()}-${String(new Date(`${start}T12:00:00.000Z`).getUTCMonth()+2).padStart(2,'0')}-01`;
  const [calculations,exceptions,pending]=await Promise.all([
    db.query<CalculationRow>(`SELECT d.labor_date::text AS "laborDate",v.id AS "versionId",v.revision,v.expected_minutes AS "expectedMinutes",v.effective_minutes AS "effectiveMinutes",v.difference_minutes AS "differenceMinutes",v.incidents FROM daily_calculations d JOIN daily_calculation_versions v ON v.id=d.current_version_id WHERE d.employee_id=$1 AND d.labor_date>=$2::date AND d.labor_date<$3::date ORDER BY d.labor_date`,[employeeId,start,end]),
    db.query<ExceptionRow>(`SELECT value.date::text AS date,max(value.holiday) AS holiday,max(value.leave) AS leave FROM (SELECT h.holiday_date AS date,h.holiday_type::text AS holiday,NULL::text AS leave FROM planning_site_holidays h JOIN employments em ON em.site_id=h.site_id WHERE em.employee_id=$1 AND em.effective_from<=h.holiday_date AND (em.effective_to IS NULL OR em.effective_to>h.holiday_date) AND h.holiday_date>=$2::date AND h.holiday_date<$3::date UNION ALL SELECT gs::date,NULL::text,l.category::text FROM leave_requests l CROSS JOIN LATERAL generate_series(l.from_date,l.to_date,'1 day') gs WHERE l.employee_id=$1 AND l.status='approved' AND l.category IN ('vacation','absence') AND gs>=$2::date AND gs<$3::date) value GROUP BY value.date`,[employeeId,start,end]),
    db.query<PendingRow>(`SELECT labor_date::text AS "laborDate",count(*)::int AS count FROM correction_requests WHERE employee_id=$1 AND status='pending' AND labor_date>=$2::date AND labor_date<$3::date GROUP BY labor_date`,[employeeId,start,end])
  ]);
  const byDate=new Map<string,MonthlyReviewDay>();for(const row of calculations.rows)byDate.set(row.laborDate,{laborDate:row.laborDate,expectedMinutes:row.expectedMinutes,effectiveMinutes:row.effectiveMinutes,differenceMinutes:row.differenceMinutes,incidents:row.incidents.length,pendingCorrections:0,holiday:null,leave:null});for(const row of exceptions.rows){const current=byDate.get(row.date)??{laborDate:row.date,expectedMinutes:null,effectiveMinutes:null,differenceMinutes:null,incidents:0,pendingCorrections:0,holiday:null,leave:null};current.holiday=row.holiday;current.leave=row.leave;byDate.set(row.date,current);}for(const row of pending.rows){const current=byDate.get(row.laborDate)??{laborDate:row.laborDate,expectedMinutes:null,effectiveMinutes:null,differenceMinutes:null,incidents:0,pendingCorrections:0,holiday:null,leave:null};current.pendingCorrections=row.count;byDate.set(row.laborDate,current);}return {days:[...byDate.values()].sort((a,b)=>a.laborDate.localeCompare(b.laborDate)),snapshotHash:hash(calculations.rows.map(row=>[row.laborDate,row.versionId,row.revision]))};
}
export async function monthlyReview(actor:ScopedActor,period:string):Promise<MonthlyReview>{await assertAvailable();const own=await context(actor);assertPeriod(period,own.currentPeriod);const current=await data(own.employeeId,period);const last=(await db.query<{reviewedAt:Date;snapshotHash:string}>('SELECT reviewed_at AS "reviewedAt",snapshot_hash AS "snapshotHash" FROM monthly_period_reviews WHERE employee_id=$1 AND period_start=$2::date ORDER BY reviewed_at DESC LIMIT 1',[own.employeeId,monthStart(period)])).rows[0];const status=current.days.length===0?'no_data':!last?'ready':last.snapshotHash===current.snapshotHash?'reviewed':'requires_review';return {period,availablePeriods:priorMonths(own.currentPeriod),timeZone:own.timeZone,days:current.days,status,reviewedAt:last?.reviewedAt.toISOString()??null,summary:summarize(current.days)};}
export async function defaultMonthlyPeriod(actor:ScopedActor){const own=await context(actor);return priorMonths(own.currentPeriod,1)[0];}
export async function markMonthlyReview(actor:ScopedActor,period:string,idempotencyKey:string,cid:string){await assertAvailable();assertAuthorized(actor,'monthly-review.create:self');const own=await context(actor);assertPeriod(period,own.currentPeriod);const current=await data(own.employeeId,period);if(!current.days.length)throw new Error('MONTHLY_REVIEW_EMPTY');const client=await db.connect();try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1, 4010))',[`${own.employeeId}:${period}`]);const existing=(await client.query<{id:string}>('SELECT id FROM monthly_period_reviews WHERE employee_id=$1 AND idempotency_key=$2',[own.employeeId,idempotencyKey])).rows[0];if(!existing){const previous=(await client.query<{snapshotHash:string}>('SELECT snapshot_hash AS "snapshotHash" FROM monthly_period_reviews WHERE employee_id=$1 AND period_start=$2::date ORDER BY reviewed_at DESC LIMIT 1',[own.employeeId,monthStart(period)])).rows[0];if(!previous||previous.snapshotHash!==current.snapshotHash){const row=(await client.query<{id:string}>(`INSERT INTO monthly_period_reviews(employee_id,period_start,snapshot_hash,reviewed_by_user_id,idempotency_key,correlation_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING id`,[own.employeeId,monthStart(period),current.snapshotHash,actor.id,idempotencyKey,cid])).rows[0];await appendAudit({actorType:'user',actorId:actor.id,action:'monthly-review.marked',resourceType:'monthly-period-review',resourceId:row.id,result:'success',correlationId:cid,changes:{period,calculationDays:current.days.filter(day=>day.effectiveMinutes!==null).length}});}}
    await client.query('COMMIT');return monthlyReview(actor,period);
  }catch(error){await client.query('ROLLBACK').catch(()=>undefined);throw error;}finally{client.release();}}
