import type { CorrectionRequest } from '@/corrections/contracts';
type Envelope<T>={data:T;error?:{message?:string};correlationId?:string};
export class AdminApiError extends Error { constructor(readonly status:number){super('No se pudo completar la consulta.');this.name='AdminApiError';} }
async function request<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{credentials:'same-origin',...init});const body=await response.json().catch(()=>null) as Envelope<T>;if(!response.ok)throw new AdminApiError(response.status);return body.data;}
export type Site={id:string;name:string;timeZone:string}; export type Employee={id:string;displayName:string;userId?:string|null}; export type Employment={id:string;employeeId:string;siteId:string;managerEmployeeId?:string|null;effectiveFrom:string;effectiveTo?:string|null;siteName?:string}; export type OnboardingRow={rowId:string;displayName:string;siteId:string;managerEmployeeId:string|null;effectiveFrom:string}; export type OnboardingPreview={rowId:string;status:'ready'|'needs_review'|'error';messages:string[]};
export const adminApi={
  sites:()=>request<Site[]>('/api/v1/sites'), employees:()=>request<Employee[]>('/api/v1/employees'), employments:()=>request<Employment[]>('/api/v1/employments'),
  createEmployee:(input:{displayName:string})=>request<Employee>('/api/v1/employees',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)}), updateEmployee:(id:string,input:{displayName:string})=>request<Employee>(`/api/v1/employees/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(input)}), deleteEmployee:(id:string)=>request<Employee>(`/api/v1/employees/${id}`,{method:'DELETE'}),
  createEmployment:(input:{employeeId:string;siteId:string;managerEmployeeId:string|null;effectiveFrom:string;effectiveTo:string|null})=>request<Employment>('/api/v1/employments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)}), updateEmployment:(id:string,input:{employeeId:string;siteId:string;managerEmployeeId:string|null;effectiveFrom:string;effectiveTo:string|null})=>request<Employment>(`/api/v1/employments/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(input)}),
  transferEmployment:(id:string,input:{siteId:string;managerEmployeeId:string|null;effectiveFrom:string})=>request<{previousEmploymentId:string;employment:Employment}>(`/api/v1/employments/${id}/transfer`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)}),
  previewOnboarding:(rows:OnboardingRow[])=>request<{rows:OnboardingPreview[]}>('/api/v1/onboarding/preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({rows})}), confirmOnboarding:(row:OnboardingRow,key:string)=>request<{employeeId:string;employmentId:string;replayed:boolean}>('/api/v1/onboarding/confirm',{method:'POST',headers:{'content-type':'application/json','idempotency-key':key},body:JSON.stringify(row)}),
  corrections:()=>request<{corrections:CorrectionRequest[]}>('/api/v1/corrections').then((v)=>v.corrections),
  workdays:(filters:{from:string;to:string;employeeId?:string;siteId?:string;incident?:string;detail?:boolean})=>{const params=new URLSearchParams({from:filters.from,to:filters.to,incident:filters.incident??'all'});if(filters.employeeId)params.set('employeeId',filters.employeeId);if(filters.siteId)params.set('siteId',filters.siteId);if(filters.detail)params.set('detail','true');return request<{workdays:any[]}>(`/api/v1/admin/workdays?${params}`).then((v)=>v.workdays);},
  events:(employeeId:string)=>request<{events:any[]}>('/api/v1/time-events?employeeId='+encodeURIComponent(employeeId)).then((v)=>v.events??[]),
  decide:(id:string,input:{decision:'approved'|'rejected';reason?:string})=>request<{correction:CorrectionRequest}>(`/api/v1/corrections/${id}/decision`,{method:'POST',headers:{'content-type':'application/json','idempotency-key':crypto.randomUUID()},body:JSON.stringify(input)}).then((v)=>v.correction)
};
