'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { StatusBadge, StatusNotice } from '@/ui/feedback';
import { ReadRecoveryNotice } from '@/ui/read-recovery-notice';
import { WorkspaceNav } from '@/ui/workspace-nav';
import { useModuleEnabled } from '@/modules/ui';
import type { CorrectionRequest } from '@/corrections/contracts';
import type { AdminWorkday } from './contracts';
import { adminApi, AdminApiError, type Employee, type Site } from './api';
import { PeopleManagement } from './people-management';
import { correctionLabel, dateTime, dateToday, eventLabel, isoWeekStart, minutes } from './presentation';
function Notice({ children, error = false }: {
    children: React.ReactNode;
    error?: boolean;
}) { return <StatusNotice kind={error ? 'error' : 'info'}>{children}</StatusNotice>; }
const correctionKind = (status: CorrectionRequest['status']) => status === 'approved' ? 'success' : status === 'rejected' ? 'error' : 'warning';
export function AdminNav() { const planningEnabled = useModuleEnabled('shift_planning'); const peopleEnabled = useModuleEnabled('people_management'); return <WorkspaceNav ariaLabel="Administración" variant="admin" items={[{ href: '/admin', label: 'Resumen' }, ...(peopleEnabled ? [{ href: '/admin/people', label: 'Personas' }] : []), { href: '/admin/corrections', label: 'Trazabilidad' }, ...(planningEnabled ? [{ href: '/admin/planning', label: 'Planificación' }] : [])]} secondaryItems={[{ href: '/admin/configuration', label: 'Configuración' }]}/>; }
function useScope() { const [state, setState] = useState<{
    sites: Site[];
    employees: Employee[];
    corrections: CorrectionRequest[];
    error?: string;
}>({ sites: [], employees: [], corrections: [] }); useEffect(() => { Promise.all([adminApi.sites(), adminApi.employees(), adminApi.corrections()]).then(([sites, employees, corrections]) => setState({ sites, employees, corrections })).catch((error) => setState({ sites: [], employees: [], corrections: [], error: error instanceof Error ? error.message : 'No se pudieron cargar los datos.' })); }, []); return state; }
export function AdminDashboard() { const { sites, employees, corrections, error } = useScope(); const peopleEnabled = useModuleEnabled('people_management'); const [workdays, setWorkdays] = useState<AdminWorkday[]>([]); const [dayError, setDayError] = useState<string>(); useEffect(() => { adminApi.workdays({ from: isoWeekStart(), to: dateToday(), incident: 'with_incidents' }).then(setWorkdays).catch((e) => setDayError(e instanceof Error ? e.message : 'No se pudieron consultar incidencias.')); }, []); const pending = corrections.filter((item) => item.status === 'pending'); return <main className="admin-shell"><AdminNav /><header><p className="eyebrow">ADMINISTRACIÓN Y RR. HH.</p><h1>Centro de administración</h1><p className="subtle">Consulta el estado operativo de tu ámbito. Las tarjetas no cambian configuración ni toman decisiones.</p></header>{error && <Notice error>{error}</Notice>}<section className="admin-cards" aria-label="Resumen operativo"><article><strong>{sites.length}</strong><span>Centros configurados</span><Link href="/admin/configuration">Abrir configuración</Link></article>{peopleEnabled && <article><strong>{employees.length}</strong><span>Personas disponibles</span><Link href="/admin/people">Ver plantilla</Link></article>}<article><strong>{pending.length}</strong><span>Correcciones pendientes</span><Link href="/admin/corrections">Abrir trazabilidad</Link></article>{peopleEnabled && <article><strong>{workdays.length}</strong><span>Jornadas con incidencia</span><Link href="/admin/people?incident=with_incidents">Ver jornadas</Link></article>}</section>{dayError && <Notice error>{dayError}</Notice>}</main>; }
export function People(){return <main className="admin-shell"><AdminNav/><PeopleManagement/></main>;}

function WorkdayDetail({ day }: {
    day: AdminWorkday;
}) { const [events, setEvents] = useState(day.events); const [loaded, setLoaded] = useState((day.events?.length ?? 0) > 0); useEffect(() => { if (!loaded)
    adminApi.events(day.employee.id).then((items) => setEvents(items.filter((item) => item.laborDate === day.calculation.laborDate))).catch(() => setEvents([])).finally(() => setLoaded(true)); }, [day.employee.id, day.calculation.laborDate, loaded]); return <section className="admin-section"><h2>{day.employee.displayName} · {day.calculation.laborDate}</h2><dl className="admin-metrics"><div><dt>Tiempo efectivo</dt><dd>{minutes(day.calculation.effectiveMinutes)}</dd></div><div><dt>Pausas</dt><dd>{minutes(day.calculation.registeredBreakMinutes)}</dd></div><div><dt>Diferencia registrada</dt><dd>{minutes(day.calculation.differenceMinutes)}</dd></div></dl><p className="informative">La diferencia es informativa; no es nómina ni una decisión económica definitiva.</p><details className="technical-details"><summary>Información técnica de cálculo</summary><p>Regla: <code>{day.calculation.ruleVersionId}</code> · algoritmo <code>{day.calculation.algorithmVersion}</code> · zona {day.calculation.effectiveTimeZone}.</p></details><h3>Eventos y pausas originales</h3>{!loaded ? <p className="subtle">Cargando eventos originales…</p> : events?.length ? <ul className="admin-list">{events.map((event) => <li key={event.id}><span><strong>{eventLabel[event.eventType]}</strong><small>{dateTime(event.occurredAt, event.effectiveTimeZone)} · {event.method === 'web' ? 'Web' : 'Kiosco'}</small></span></li>)}</ul> : <p className="subtle">No hay eventos originales para esta jornada.</p>}{day.calculation.incidents.length > 0 && <><h3>Incidencias</h3><ul>{day.calculation.incidents.map((item, index) => <li key={`${item.code}-${index}`}>{item.message}</li>)}</ul></>}</section>; }
export function Corrections() { const { employees, corrections, error } = useScope(); const [status, setStatus] = useState('pending'); const filtered = useMemo(() => corrections.filter((item) => status === 'all' || item.status === status), [corrections, status]); return <main className="admin-shell"><AdminNav /><h1>Trazabilidad de correcciones</h1><p className="subtle">Consulta la evidencia y las decisiones registradas. La aprobación o rechazo corresponde exclusivamente al responsable del centro.</p><label className="ui-field ui-filter">Estado<select className="ui-control" value={status} onChange={(e) => setStatus(e.target.value)}><option value="pending">Pendientes</option><option value="approved">Aprobadas</option><option value="rejected">Rechazadas</option><option value="all">Todos</option></select></label>{error && <Notice error>{error}</Notice>}<section className="admin-section">{!filtered.length ? <p className="subtle">No hay solicitudes con este estado en tu ámbito.</p> : <ul className="admin-list">{filtered.map((item) => <li key={item.id}><span><StatusBadge kind={correctionKind(item.status)}>{correctionLabel[item.status]}</StatusBadge><strong>{employees.find((employee) => employee.id === item.employeeId)?.displayName ?? 'Persona autorizada'}</strong><small>{item.laborDate} · solicitada {new Date(item.requestedAt).toLocaleString('es-ES')} · {item.reason}</small></span><Link href={`/admin/corrections/${item.id}`}>Ver trazabilidad</Link></li>)}</ul>}</section></main>; }
export function CorrectionDetail({ id }: {
    id: string;
}) {
    const { employees, corrections, error } = useScope();
    const item = corrections.find((value) => value.id === id);
    return <main className="admin-shell"><AdminNav /><Link href="/admin/corrections">← Volver a trazabilidad</Link><h1>Detalle de corrección</h1><p className="subtle">Consulta de evidencia y decisiones registradas. La aprobación o rechazo corresponde exclusivamente al responsable del centro.</p>{error && <Notice error>{error}</Notice>}{!item ? <p className="subtle">La solicitud no existe o está fuera de tu ámbito.</p> : <section className="admin-section"><dl className="admin-detail"><div><dt>Persona</dt><dd>{employees.find((employee) => employee.id === item.employeeId)?.displayName ?? 'Persona autorizada'}</dd></div><div><dt>Estado de la solicitud</dt><dd><StatusBadge kind={correctionKind(item.status)}>{correctionLabel[item.status]}</StatusBadge> · {new Date(item.requestedAt).toLocaleString('es-ES')}</dd></div><div><dt>Origen</dt><dd>{item.kind === 'time_event' ? 'Fichaje original' : 'Incidencia de cálculo'}</dd></div><div><dt>Propuesta</dt><dd>{eventLabel[item.proposedEffect.eventType]} · {dateTime(item.proposedEffect.occurredAt, 'Europe/Madrid')}</dd></div><div><dt>Motivo del solicitante</dt><dd>{item.reason}</dd></div>{item.decision && <div><dt>Decisión registrada</dt><dd>{item.decision.decision === 'approved' ? 'Aprobada' : 'Rechazada'} · {new Date(item.decision.decidedAt).toLocaleString('es-ES')}{item.decision.reason ? ` · ${item.decision.reason}` : ''}</dd></div>}</dl><details className="technical-details"><summary>Referencias técnicas de auditoría</summary><p>Solicitud: <code>{item.id}</code> · origen: <code>{item.kind === 'time_event' ? item.timeEventId : item.dailyCalculationVersionId}</code>{item.decision && <> · actor: <code>{item.decision.decidedByUserId}</code></>}</p></details></section>}</main>;
}
