'use client';
import {useEffect,useMemo,useState} from 'react';
import {adminApi,type Employee,type Employment,type OnboardingPreview,type OnboardingRow,type Site} from './api';

const today=()=>new Date().toISOString().slice(0,10);
type Row=OnboardingRow&{key:string;confirmationKey:string};
const newRow=():Row=>({key:crypto.randomUUID(),confirmationKey:crypto.randomUUID(),rowId:crypto.randomUUID(),displayName:'',siteId:'',managerEmployeeId:null,effectiveFrom:today()});

function AssistedOnboarding({sites,employees,onConfirmed,onCancel}:{sites:Site[];employees:Employee[];onConfirmed:()=>void;onCancel:()=>void}){
 const [rows,setRows]=useState<Row[]>([newRow()]),[preview,setPreview]=useState<Record<string,OnboardingPreview>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const clear=(id:string)=>setPreview(value=>{const {[id]:_,...rest}=value;return rest;});
 const update=(key:string,field:keyof OnboardingRow,value:string|null)=>setRows(items=>items.map(row=>{if(row.key!==key)return row;clear(row.rowId);return {...row,[field]:value,confirmationKey:crypto.randomUUID()};}));
 const inspect=async()=>{setBusy(true);setMessage('');try{const result=await adminApi.previewOnboarding(rows.map(({key,confirmationKey,...row})=>row));setPreview(Object.fromEntries(result.rows.map(row=>[row.rowId,row])));}catch{setMessage('No se pudo validar la preparación.');}finally{setBusy(false);}};
 const confirm=async(row:Row)=>{setBusy(true);setMessage('');try{await adminApi.confirmOnboarding(row,row.confirmationKey);clear(row.rowId);setRows(items=>items.filter(item=>item.key!==row.key));onConfirmed();}catch{setMessage('No se pudo confirmar la fila.');}finally{setBusy(false);}};
 return <section className="admin-section onboarding" aria-labelledby="create-people-title"><div className="section-heading"><div><h2 id="create-people-title">Crear personas</h2><p className="subtle">Prepare hasta 25 altas. Cada confirmación crea una persona y su relación con el centro, pero no una cuenta de acceso.</p></div><button type="button" className="secondary" disabled={busy||rows.length>=25} onClick={()=>setRows(items=>[...items,newRow()])}>Añadir fila</button></div>{message&&<p className="status-notice status-notice--error" role="status">{message}</p>}<div className="onboarding__rows">{rows.map((row,index)=>{const state=preview[row.rowId];return <fieldset key={row.key}><legend>Fila {index+1}</legend><label>Nombre visible<input className="ui-control" value={row.displayName} maxLength={160} onChange={event=>update(row.key,'displayName',event.target.value)}/></label><label>Centro<select className="ui-control" value={row.siteId} onChange={event=>update(row.key,'siteId',event.target.value)}><option value="">Seleccione un centro</option>{sites.map(site=><option key={site.id} value={site.id}>{site.name}</option>)}</select></label><label>Responsable <span className="optional">opcional</span><select className="ui-control" value={row.managerEmployeeId??''} onChange={event=>update(row.key,'managerEmployeeId',event.target.value||null)}><option value="">Sin responsable</option>{employees.filter(person=>person.id!==row.managerEmployeeId).map(person=><option key={person.id} value={person.id}>{person.displayName}</option>)}</select></label><label>Vigente desde<input className="ui-control" type="date" value={row.effectiveFrom} onChange={event=>update(row.key,'effectiveFrom',event.target.value)}/></label>{state&&<p className={`onboarding__state onboarding__state--${state.status}`}><strong>{state.status==='ready'?'Lista para confirmar':state.status==='needs_review'?'Requiere revisión':'Corrija esta fila'}</strong>{state.messages.map(text=><span key={text}>{text}</span>)}</p>}<div className="onboarding__actions"><button type="button" className="secondary" disabled={busy||rows.length===1} onClick={()=>{clear(row.rowId);setRows(items=>items.filter(item=>item.key!==row.key));}}>Quitar</button><button type="button" disabled={busy||state?.status!=='ready'} onClick={()=>void confirm(row)}>Confirmar fila</button></div></fieldset>;})}</div><div className="onboarding__footer"><button type="button" onClick={()=>void inspect()} disabled={busy}>{busy?'Validando…':'Validar preparación'}</button><button type="button" className="secondary" onClick={onCancel} disabled={busy}>Cancelar</button></div></section>;
}

export function PeopleManagement(){
 const [sites,setSites]=useState<Site[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[employments,setEmployments]=useState<Employment[]>([]),[loading,setLoading]=useState(true),[showCreate,setShowCreate]=useState(false),[editing,setEditing]=useState<Employee>(),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{setLoading(true);try{const [nextSites,nextEmployees,nextEmployments]=await Promise.all([adminApi.sites(),adminApi.employees(),adminApi.employments()]);setSites(nextSites);setEmployees(nextEmployees);setEmployments(nextEmployments);}catch{setMessage('No se pudo cargar la plantilla.');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const activeEmployment=(employeeId:string)=>employments.find(item=>item.employeeId===employeeId&&!item.effectiveTo);
 const people=useMemo(()=>employees.map(employee=>({employee,employment:activeEmployment(employee.id)})),[employees,employments]);
 const save=async(form:FormData)=>{if(!editing)return;setBusy(true);setMessage('');try{await adminApi.updateEmployee(editing.id,{displayName:String(form.get('displayName')).trim()});const input={employeeId:editing.id,siteId:String(form.get('siteId')),managerEmployeeId:String(form.get('managerEmployeeId'))||null,effectiveFrom:String(form.get('effectiveFrom')),effectiveTo:null};const employment=activeEmployment(editing.id);if(employment)await adminApi.updateEmployment(employment.id,input);else await adminApi.createEmployment(input);setEditing(undefined);setMessage('Persona actualizada.');await load();}catch{setMessage('No se pudo actualizar la persona. Revise el centro, responsable y fechas.');}finally{setBusy(false);}};
 const remove=async(employee:Employee)=>{if(!window.confirm(`¿Dar de baja a ${employee.displayName}? Se conservará el histórico, pero dejará de estar disponible para nuevas asignaciones.`))return;setBusy(true);setMessage('');try{await adminApi.deleteEmployee(employee.id);setMessage('Persona dada de baja. Se conserva su trazabilidad.');await load();}catch{setMessage('No se pudo dar de baja la persona.');}finally{setBusy(false);}};
 const current=editing?activeEmployment(editing.id):undefined;
 if(loading)return <section className="people-management"><header><p className="eyebrow">GESTIÓN DE PERSONAS</p><h1>Plantilla</h1><p className="subtle">Preparando personas, centros y relaciones vigentes…</p></header><section className="admin-section people-management__loading" role="status" aria-live="polite">Cargando plantilla…</section></section>;
 return <section className="people-management"><header><p className="eyebrow">GESTIÓN DE PERSONAS</p><h1>Plantilla</h1><p className="subtle">Administre las personas de la organización y su relación vigente con cada centro. Una persona no recibe acceso ni puede fichar hasta que se habilite una cuenta mediante un flujo separado.</p></header>{message&&<p className="status-notice" role="status">{message}</p>}<section className="admin-section"><div className="section-heading"><div><h2>Personas activas</h2><p className="subtle">Editar modifica su nombre y relación vigente. La baja es lógica y preserva el histórico.</p></div><button type="button" onClick={()=>setShowCreate(value=>!value)} aria-expanded={showCreate}>{showCreate?'Cerrar alta':'Nueva persona'}</button></div>{!people.length?<p className="subtle">No hay personas activas.</p>:<ul className="admin-list people-management__list">{people.map(({employee,employment})=><li key={employee.id}><span><strong>{employee.displayName}</strong><small>{employment?`${sites.find(site=>site.id===employment.siteId)?.name??employment.siteName??'Centro'} · vigente desde ${employment.effectiveFrom}`:'Sin relación laboral vigente'} · sin cuenta de acceso</small></span><span className="people-management__actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setEditing(employee)}>Editar</button><button type="button" className="danger" disabled={busy} onClick={()=>void remove(employee)}>Dar de baja</button></span></li>)}</ul>}</section>{showCreate&&<AssistedOnboarding sites={sites} employees={employees} onConfirmed={()=>void load()} onCancel={()=>setShowCreate(false)}/>} {editing&&<section className="admin-section"><div className="section-heading"><div><h2>Editar persona</h2><p className="subtle">Los cambios no reescriben fichajes ni asignaciones históricas.</p></div><button type="button" className="secondary" onClick={()=>setEditing(undefined)}>Cancelar</button></div><form className="configuration-form" onSubmit={event=>{event.preventDefault();void save(new FormData(event.currentTarget));}}><label>Nombre visible<input name="displayName" required maxLength={160} defaultValue={editing.displayName}/></label><label>Centro<select name="siteId" required defaultValue={current?.siteId??''}><option value="">Seleccione un centro</option>{sites.map(site=><option key={site.id} value={site.id}>{site.name}</option>)}</select></label><label>Responsable <span className="optional">opcional</span><select name="managerEmployeeId" defaultValue={current?.managerEmployeeId??''}><option value="">Sin responsable</option>{employees.filter(employee=>employee.id!==editing.id).map(employee=><option key={employee.id} value={employee.id}>{employee.displayName}</option>)}</select></label><label>Vigente desde<input name="effectiveFrom" type="date" required defaultValue={current?.effectiveFrom??today()}/></label><button disabled={busy}>{busy?'Guardando…':'Guardar cambios'}</button></form></section>}</section>;
}
