import { createHash, randomUUID } from 'node:crypto';
import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { db } from '@/shared/db';
import { config } from '@/shared/config';
import { appendAudit } from '@/audit/audit-writer';
import { assertAuthorized, assertSiteScope, type ScopedActor } from '@/permissions/authorizer';
import { EXPORT_TEMPLATE_VERSION, type ExportManifest, type ExportRequest, type ExportSnapshot } from './contracts';

export { renderCsv, renderPdf };

const sha=(value:Buffer|string)=>createHash('sha256').update(value).digest('hex');
export const integrityHash=sha;
const stable=(value:unknown)=>JSON.stringify(value);
const root=()=>config.EXPORT_STORAGE_DIR ?? path.join(process.cwd(),'.exports');
const minutes=(n:number)=>`${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;
function csvCell(value:unknown){const text=String(value??'');return /[",\r\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text;}
function renderCsv(snapshot:ExportSnapshot){const rows=['Empresa,Centro,Empleado,Fecha,Zona,Inicio,Fin,Pausas,Tiempo efectivo,Jornada esperada,Incidencias,Correcciones,Regla/version']; for(const r of snapshot.records){const first=r.events.find(e=>e.type==='clock_in')?.occurredAt??'';const last=[...r.events].reverse().find(e=>e.type==='clock_out')?.occurredAt??'';const pauses=r.events.filter(e=>e.type.startsWith('break_')).map(e=>`${e.type}:${e.occurredAt}`).join(' | ');const c=r.calculation;rows.push([snapshot.company,r.site,r.employee,r.laborDate,r.timeZone,first,last,pauses,c?minutes(c.effectiveMinutes):'',c?minutes(c.expectedMinutes):'',c?JSON.stringify(c.incidents):'',r.corrections.map(x=>`${x.status} ${x.sourceEventId??'incidencia'} -> ${x.effect?.occurredAt??''}`).join(' | '),c?`${c.ruleName}/${c.ruleVersionId}`:''].map(csvCell).join(','));}return Buffer.from('\uFEFF'+rows.join('\r\n'),'utf8');}
function pdfText(value:string){return value.replace(/[\\()]/g,'\\$&').replace(/[^\x20-\xff]/g,'?');}
function renderPdf(snapshot:ExportSnapshot){const lines=[`Registro de jornada - ${snapshot.company}`,`Periodo: ${snapshot.from} a ${snapshot.to}`,'' ,...snapshot.records.flatMap(r=>[`${r.employee} | ${r.site} | ${r.laborDate} (${r.timeZone})`,`Inicio: ${r.events.find(e=>e.type==='clock_in')?.occurredAt??'-'}  Fin: ${[...r.events].reverse().find(e=>e.type==='clock_out')?.occurredAt??'-'}`,`Pausas: ${r.events.filter(e=>e.type.startsWith('break_')).map(e=>e.occurredAt).join(', ')||'-'}`,`Efectivo/esperado: ${r.calculation?`${minutes(r.calculation.effectiveMinutes)}/${minutes(r.calculation.expectedMinutes)}`:'sin cálculo'} | Regla: ${r.calculation?`${r.calculation.ruleName} (${r.calculation.ruleVersionId})`:'-'}`,`Incidencias: ${r.calculation?JSON.stringify(r.calculation.incidents):'-'}`,`Correcciones: ${r.corrections.map(c=>`${c.status}, fuente ${c.sourceEventId??'incidencia'}, efecto ${c.effect?.occurredAt??'-'}`).join(' | ')||'-'}`,''])].slice(0,45);const stream=lines.map((line,i)=>`${i?'0 -14 Td':''} (${pdfText(line)}) Tj`).join('\n');const body=`BT\n/F1 10 Tf\n50 780 Td\n${stream}\nET`;const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${Buffer.byteLength(body,'latin1')} >>\nstream\n${body}\nendstream`];let output='%PDF-1.4\n';const offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(output,'latin1'));output+=`${i+1} 0 obj\n${o}\nendobj\n`;});const xref=Buffer.byteLength(output,'latin1');output+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer << /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(output,'latin1');}
async function snapshot(actor:ScopedActor,input:ExportRequest):Promise<ExportSnapshot>{const params:unknown[]=[config.ENVIRONMENT_ID,input.from,input.to];let filter='';if(input.employeeId){params.push(input.employeeId);filter+=` AND e.id=$${params.length}`;}if(input.siteId){params.push(input.siteId);filter+=` AND s.id=$${params.length}`;}const scope=actor.scopes?.filter(x=>x.type==='site'&&x.id).map(x=>x.id!)??[];if(!actor.scopes?.some(x=>x.type==='environment')){params.push(scope);filter+=` AND s.id=ANY($${params.length}::uuid[])`;}const company=await db.query<{name:string}>('SELECT name FROM companies WHERE environment_id=$1',[config.ENVIRONMENT_ID]);const days=await db.query<any>(`SELECT e.id AS "employeeId",e.display_name AS employee,s.id AS "siteId",s.name AS site,d.labor_date::text AS "laborDate",v.effective_time_zone AS "timeZone",v.id AS "calculationId",v.revision,v.effective_minutes AS "effectiveMinutes",v.expected_minutes AS "expectedMinutes",v.registered_break_minutes AS "breakMinutes",v.incidents,v.rule_version_id AS "ruleVersionId",wr.name AS "ruleName",v.algorithm_version AS "algorithmVersion" FROM daily_calculations d JOIN daily_calculation_versions v ON v.id=d.current_version_id JOIN employees e ON e.id=d.employee_id JOIN sites s ON s.id=d.site_id JOIN companies c ON c.id=e.company_id JOIN rule_versions rv ON rv.id=v.rule_version_id JOIN work_rules wr ON wr.id=rv.work_rule_id WHERE c.environment_id=$1 AND d.labor_date BETWEEN $2::date AND $3::date${filter} ORDER BY d.labor_date,e.display_name`,params);const records=await Promise.all(days.rows.map(async d=>{const events=(await db.query<any>('SELECT id,event_type AS type,occurred_at AS "occurredAt" FROM time_events WHERE employee_id=$1 AND labor_date=$2::date ORDER BY occurred_at,id',[d.employeeId,d.laborDate])).rows.map(x=>({...x,occurredAt:x.occurredAt.toISOString()}));const corrections=(await db.query<any>('SELECT r.id,r.status,r.reason,r.time_event_id AS "sourceEventId",ef.id AS "effectId",ef.event_type AS type,ef.occurred_at AS "effectAt" FROM correction_requests r LEFT JOIN correction_effects ef ON ef.correction_request_id=r.id WHERE r.employee_id=$1 AND r.labor_date=$2::date ORDER BY r.requested_at,id',[d.employeeId,d.laborDate])).rows.map(x=>({id:x.id,status:x.status,reason:x.reason,sourceEventId:x.sourceEventId,effect:x.effectId?{id:x.effectId,type:x.type,occurredAt:x.effectAt.toISOString()}:null}));return {employeeId:d.employeeId,employee:d.employee,siteId:d.siteId,site:d.site,laborDate:d.laborDate,timeZone:d.timeZone,events,calculation:{id:d.calculationId,revision:d.revision,effectiveMinutes:d.effectiveMinutes,expectedMinutes:d.expectedMinutes,breakMinutes:d.breakMinutes,incidents:d.incidents,ruleVersionId:d.ruleVersionId,ruleName:d.ruleName,algorithmVersion:d.algorithmVersion},corrections};}));return {company:company.rows[0]?.name??'',scope:input.employeeId?'employee':'site',from:input.from,to:input.to,records};}
export async function createExport(actor:ScopedActor,input:ExportRequest,cid:string){assertAuthorized(actor,'export.create:scope');if(!input.employeeId&&!input.siteId)throw new Error('EXPORT_SCOPE_TOO_BROAD');if(input.siteId)assertSiteScope(actor,input.siteId);if(input.employeeId){const target=await db.query<{siteId:string;userId:string|null}>('SELECT em.site_id AS "siteId",e.user_id AS "userId" FROM employees e JOIN employments em ON em.employee_id=e.id AND em.effective_to IS NULL WHERE e.id=$1',[input.employeeId]);if(!target.rowCount)throw new Error('EXPORT_NOT_FOUND');if(target.rows[0].userId===actor.id){if(!actor.permissions.has('time-event.read:self'))throw new Error('FORBIDDEN');}else assertSiteScope(actor,target.rows[0].siteId);}const data=await snapshot(actor,input);const exportId=randomUUID();const bytes=input.format==='csv'?renderCsv(data):renderPdf(data);const contentHash=sha(bytes);const generatedAt=new Date().toISOString();const manifest:ExportManifest={exportId,generatedAt,actorId:actor.id,parameters:input,templateVersion:EXPORT_TEMPLATE_VERSION,contentHash,snapshotHash:sha(stable(data))};const key=`${exportId}.${input.format}`;await mkdir(root(),{recursive:true});await writeFile(path.join(root(),key),bytes,{flag:'wx'});try{await db.query('INSERT INTO exports(id,requested_by_user_id,format,scope_type,employee_id,site_id,period_from,period_to,snapshot,manifest,content_hash,storage_key,template_version,generated_at,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)',[exportId,actor.id,input.format,data.scope,input.employeeId??null,input.siteId??null,input.from,input.to,JSON.stringify(data),JSON.stringify(manifest),contentHash,key,EXPORT_TEMPLATE_VERSION,generatedAt,new Date(Date.now()+30*86400000)]);await appendAudit({actorType:'user',actorId:actor.id,action:'export.generated',resourceType:'export',resourceId:exportId,result:'success',correlationId:cid,changes:{format:input.format,scope:data.scope,from:input.from,to:input.to,contentHash}});return {id:exportId,manifest};}catch(e){await unlink(path.join(root(),key)).catch(()=>undefined);throw e;}}
export async function downloadExport(actor:ScopedActor,id:string,cid:string){assertAuthorized(actor,'export.read:scope');const q=await db.query<any>('SELECT * FROM exports WHERE id=$1',[id]);const item=q.rows[0];if(!item)throw new Error('EXPORT_NOT_FOUND');if(item.requested_by_user_id!==actor.id){if(item.site_id)assertSiteScope(actor,item.site_id);else throw new Error('FORBIDDEN');}if(item.status!=='available'||item.expires_at<=new Date())throw new Error('EXPORT_EXPIRED');const bytes=await readFile(path.join(root(),item.storage_key));if(sha(bytes)!==item.content_hash)throw new Error('EXPORT_INTEGRITY_FAILED');await appendAudit({actorType:'user',actorId:actor.id,action:'export.downloaded',resourceType:'export',resourceId:id,result:'success',correlationId:cid,changes:{contentHash:item.content_hash}});return {bytes,format:item.format,manifest:item.manifest};}
